load("//website:defs.bzl", "doc")

package(
    default_visibility = ["//website:__pkg__"],
    licenses = ["notice"],
)

doc(
    name = "index",
    src = "README.md",
    category = "Architecture Guide",
    data = [
        "Layers.png",
        "Layers.svg",
        "Machine-Virtualization.png",
        "Machine-Virtualization.svg",
        "Rule-Based-Execution.png",
        "Rule-Based-Execution.svg",
        "Sentry-Gofer.png",
        "Sentry-Gofer.svg",
    ],
    permalink = "/docs/architecture_guide/",
    weight = "0",
)

doc(
    name = "platforms",
    src = "platforms.md",
    category = "Architecture Guide",
    data = [
        "Sentry-Gofer.png",
        "Sentry-Gofer.svg",
    ],
    permalink = "/docs/architecture_guide/platforms/",
    weight = "40",
)

doc(
    name = "resources",
    src = "resources.md",
    category = "Architecture Guide",
    permalink = "/docs/architecture_guide/resources/",
    weight = "30",
)

doc(
    name = "security",
    src = "security.md",
    category = "Architecture Guide",
    data = [
        "Layers.png",
        "Layers.svg",
    ],
    permalink = "/docs/architecture_guide/security/",
    weight = "10",
)

doc(
    name = "performance",
    src = "performance.md",
    category = "Architecture Guide",
    permalink = "/docs/architecture_guide/performance/",
    weight = "20",
)
