steps:

# Build remotely.
- name: 'gcr.io/cloud-builders/bazel'
  args:
    - 'build'
    - '--show_timestamps'
    - '--test_output=errors'
    - '--keep_going'
    - '--verbose_failures=true'
    - '--config=remote'
    - '--project_id=${_RBE_PROJECT_ID}'
    - '--remote_instance_name=projects/${_RBE_PROJECT_ID}/instances/default_instance'
    - '//:release'
- name: 'ubuntu'
  args:
    - 'bash'
    - '-c'
    - 'mkdir -p release-files && tar -xvf bazel-bin/release.tar -C release-files'

# Upload to latest, date-tagged and tagged folder.
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if ${_LATEST}; then gsutil cp release-files gs://${_BUCKET}/latest; fi
      if ${_DATE}; then gsutil cp release-files gs://${_BUCKET}/$(date +%Y%m%d%H%M%S); fi
      if ${_TAG}; then gsutil cp release-files gs://${_BUCKET}/${TAG}; fi

substitutions:
    _RBE_PROJECT_ID: 'gvisor-rbe'
    _BUCKET: 'gvisor'
    _LATEST: 'false"
    _DATE: 'false'
    _TAG: 'false'
