load("//tools/go_stateify:defs.bzl", "go_library")

package(licenses = ["notice"])  # Apache 2.0

go_library(
    name = "kdefs",
    srcs = ["kdefs.go"],
    importpath = "gvisor.googlesource.com/gvisor/pkg/sentry/kernel/kdefs",
    visibility = ["//:sandbox"],
)
