package(licenses = ["notice"])  # Apache 2.0

load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "kdefs",
    srcs = ["kdefs.go"],
    importpath = "gvisor.googlesource.com/gvisor/pkg/sentry/kernel/kdefs",
    visibility = ["//:sandbox"],
)
