// automatically generated by stateify.

package boot

import (
	"gvisor.dev/gvisor/pkg/state"
)

func (x *sandboxNetstackCreator) beforeSave() {}
func (x *sandboxNetstackCreator) save(m state.Map) {
	x.beforeSave()
	m.Save("clock", &x.clock)
	m.Save("uniqueID", &x.uniqueID)
}

func (x *sandboxNetstackCreator) afterLoad() {}
func (x *sandboxNetstackCreator) load(m state.Map) {
	m.Load("clock", &x.clock)
	m.Load("uniqueID", &x.uniqueID)
}

func init() {
	state.Register("runsc/boot.sandboxNetstackCreator", (*sandboxNetstackCreator)(nil), state.Fns{Save: (*sandboxNetstackCreator).save, Load: (*sandboxNetstackCreator).load})
}
