load("//tools:defs.bzl", "go_library")

package(
    default_applicable_licenses = ["//:license"],
    licenses = ["notice"],
)

go_library(
    name = "gvisordetect",
    srcs = ["gvisordetect.go"],
    importpath = "gvisor.dev/gvisor/pkg/gvisordetect",
    visibility = ["//visibility:public"],
)
