load("defs.bzl", "packetdrill_test")

package(licenses = ["notice"])

packetdrill_test(
    name = "fin_wait2_timeout",
    scripts = ["fin_wait2_timeout.pkt"],
)

packetdrill_test(
    name = "tcp_noaccept_close_rst",
    scripts = ["tcp_noaccept_close_rst.pkt"],
)
