// automatically generated by stateify.

package unix

import (
	"gvisor.dev/gvisor/pkg/state"
)

func (x *socketOperationsRefs) StateTypeName() string {
	return "pkg/sentry/socket/unix.socketOperationsRefs"
}

func (x *socketOperationsRefs) StateFields() []string {
	return []string{
		"refCount",
	}
}

func (x *socketOperationsRefs) beforeSave() {}

func (x *socketOperationsRefs) StateSave(m state.Sink) {
	x.beforeSave()
	m.Save(0, &x.refCount)
}

func (x *socketOperationsRefs) afterLoad() {}

func (x *socketOperationsRefs) StateLoad(m state.Source) {
	m.Load(0, &x.refCount)
}

func (x *socketVFS2Refs) StateTypeName() string {
	return "pkg/sentry/socket/unix.socketVFS2Refs"
}

func (x *socketVFS2Refs) StateFields() []string {
	return []string{
		"refCount",
	}
}

func (x *socketVFS2Refs) beforeSave() {}

func (x *socketVFS2Refs) StateSave(m state.Sink) {
	x.beforeSave()
	m.Save(0, &x.refCount)
}

func (x *socketVFS2Refs) afterLoad() {}

func (x *socketVFS2Refs) StateLoad(m state.Source) {
	m.Load(0, &x.refCount)
}

func (x *SocketOperations) StateTypeName() string {
	return "pkg/sentry/socket/unix.SocketOperations"
}

func (x *SocketOperations) StateFields() []string {
	return []string{
		"socketOperationsRefs",
		"socketOpsCommon",
	}
}

func (x *SocketOperations) beforeSave() {}

func (x *SocketOperations) StateSave(m state.Sink) {
	x.beforeSave()
	m.Save(0, &x.socketOperationsRefs)
	m.Save(1, &x.socketOpsCommon)
}

func (x *SocketOperations) afterLoad() {}

func (x *SocketOperations) StateLoad(m state.Source) {
	m.Load(0, &x.socketOperationsRefs)
	m.Load(1, &x.socketOpsCommon)
}

func (x *socketOpsCommon) StateTypeName() string {
	return "pkg/sentry/socket/unix.socketOpsCommon"
}

func (x *socketOpsCommon) StateFields() []string {
	return []string{
		"SendReceiveTimeout",
		"ep",
		"stype",
		"abstractName",
		"abstractNamespace",
	}
}

func (x *socketOpsCommon) beforeSave() {}

func (x *socketOpsCommon) StateSave(m state.Sink) {
	x.beforeSave()
	m.Save(0, &x.SendReceiveTimeout)
	m.Save(1, &x.ep)
	m.Save(2, &x.stype)
	m.Save(3, &x.abstractName)
	m.Save(4, &x.abstractNamespace)
}

func (x *socketOpsCommon) afterLoad() {}

func (x *socketOpsCommon) StateLoad(m state.Source) {
	m.Load(0, &x.SendReceiveTimeout)
	m.Load(1, &x.ep)
	m.Load(2, &x.stype)
	m.Load(3, &x.abstractName)
	m.Load(4, &x.abstractNamespace)
}

func (x *SocketVFS2) StateTypeName() string {
	return "pkg/sentry/socket/unix.SocketVFS2"
}

func (x *SocketVFS2) StateFields() []string {
	return []string{
		"vfsfd",
		"FileDescriptionDefaultImpl",
		"DentryMetadataFileDescriptionImpl",
		"LockFD",
		"socketVFS2Refs",
		"socketOpsCommon",
	}
}

func (x *SocketVFS2) beforeSave() {}

func (x *SocketVFS2) StateSave(m state.Sink) {
	x.beforeSave()
	m.Save(0, &x.vfsfd)
	m.Save(1, &x.FileDescriptionDefaultImpl)
	m.Save(2, &x.DentryMetadataFileDescriptionImpl)
	m.Save(3, &x.LockFD)
	m.Save(4, &x.socketVFS2Refs)
	m.Save(5, &x.socketOpsCommon)
}

func (x *SocketVFS2) afterLoad() {}

func (x *SocketVFS2) StateLoad(m state.Source) {
	m.Load(0, &x.vfsfd)
	m.Load(1, &x.FileDescriptionDefaultImpl)
	m.Load(2, &x.DentryMetadataFileDescriptionImpl)
	m.Load(3, &x.LockFD)
	m.Load(4, &x.socketVFS2Refs)
	m.Load(5, &x.socketOpsCommon)
}

func init() {
	state.Register((*socketOperationsRefs)(nil))
	state.Register((*socketVFS2Refs)(nil))
	state.Register((*SocketOperations)(nil))
	state.Register((*socketOpsCommon)(nil))
	state.Register((*SocketVFS2)(nil))
}
