load("//tools:defs.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "gohacks",
    srcs = [
        "gohacks_unsafe.go",
    ],
    stateify = False,
    visibility = ["//:sandbox"],
)
