FROM python:3.10

RUN pip install torch~=2.2.0 torch_xla[tpu]~=2.2.0 torchvision -f https://storage.googleapis.com/libtpu-releases/index.html

RUN git clone --depth=1 --branch v2.0.0 https://github.com/pytorch/xla.git