FROM python:3.10

RUN pip install torch==2.5.1 torch_xla[tpu]==2.5.1 -f https://storage.googleapis.com/libtpu-releases/index.html

RUN git clone --depth=1 --branch v2.0.0 https://github.com/pytorch/xla.git