load("//website:defs.bzl", "doc")

package(
    default_visibility = ["//website:__pkg__"],
    licenses = ["notice"],
)

doc(
    name = "gsoc_2021",
    src = "gsoc-2021-ideas.md",
    category = "Project",
    include_in_menu = False,
    permalink = "/community/gsoc_2021/",
    subcategory = "Community",
    weight = "99",
)
