load("//tools:defs.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "transport",
    srcs = ["transport.go"],
    visibility = ["//visibility:public"],
    deps = ["//pkg/tcpip"],
)
