load("//tools:defs.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "testdata",
    srcs = [
        "busybox.go",
        "containerd_config.go",
        "httpd.go",
        "httpd_mount_paths.go",
        "sandbox.go",
        "simple.go",
    ],
    visibility = [
        "//visibility:public",
    ],
)
