// automatically generated by stateify.

package gofer

import (
	"gvisor.dev/gvisor/pkg/state"
)

func (f *fifo) StateTypeName() string {
	return "pkg/sentry/fs/gofer.fifo"
}

func (f *fifo) StateFields() []string {
	return []string{
		"InodeOperations",
		"fileIops",
	}
}

func (f *fifo) beforeSave() {}

func (f *fifo) StateSave(stateSinkObject state.Sink) {
	f.beforeSave()
	stateSinkObject.Save(0, &f.InodeOperations)
	stateSinkObject.Save(1, &f.fileIops)
}

func (f *fifo) afterLoad() {}

func (f *fifo) StateLoad(stateSourceObject state.Source) {
	stateSourceObject.Load(0, &f.InodeOperations)
	stateSourceObject.Load(1, &f.fileIops)
}

func (f *fileOperations) StateTypeName() string {
	return "pkg/sentry/fs/gofer.fileOperations"
}

func (f *fileOperations) StateFields() []string {
	return []string{
		"inodeOperations",
		"dirCursor",
		"flags",
	}
}

func (f *fileOperations) beforeSave() {}

func (f *fileOperations) StateSave(stateSinkObject state.Sink) {
	f.beforeSave()
	stateSinkObject.Save(0, &f.inodeOperations)
	stateSinkObject.Save(1, &f.dirCursor)
	stateSinkObject.Save(2, &f.flags)
}

func (f *fileOperations) StateLoad(stateSourceObject state.Source) {
	stateSourceObject.LoadWait(0, &f.inodeOperations)
	stateSourceObject.Load(1, &f.dirCursor)
	stateSourceObject.LoadWait(2, &f.flags)
	stateSourceObject.AfterLoad(f.afterLoad)
}

func (f *filesystem) StateTypeName() string {
	return "pkg/sentry/fs/gofer.filesystem"
}

func (f *filesystem) StateFields() []string {
	return []string{}
}

func (f *filesystem) beforeSave() {}

func (f *filesystem) StateSave(stateSinkObject state.Sink) {
	f.beforeSave()
}

func (f *filesystem) afterLoad() {}

func (f *filesystem) StateLoad(stateSourceObject state.Source) {
}

func (i *inodeOperations) StateTypeName() string {
	return "pkg/sentry/fs/gofer.inodeOperations"
}

func (i *inodeOperations) StateFields() []string {
	return []string{
		"fileState",
		"cachingInodeOps",
	}
}

func (i *inodeOperations) beforeSave() {}

func (i *inodeOperations) StateSave(stateSinkObject state.Sink) {
	i.beforeSave()
	stateSinkObject.Save(0, &i.fileState)
	stateSinkObject.Save(1, &i.cachingInodeOps)
}

func (i *inodeOperations) afterLoad() {}

func (i *inodeOperations) StateLoad(stateSourceObject state.Source) {
	stateSourceObject.LoadWait(0, &i.fileState)
	stateSourceObject.Load(1, &i.cachingInodeOps)
}

func (i *inodeFileState) StateTypeName() string {
	return "pkg/sentry/fs/gofer.inodeFileState"
}

func (i *inodeFileState) StateFields() []string {
	return []string{
		"s",
		"sattr",
		"loading",
		"savedUAttr",
		"hostMappable",
	}
}

func (i *inodeFileState) StateSave(stateSinkObject state.Sink) {
	i.beforeSave()
	var loadingValue struct{} = i.saveLoading()
	stateSinkObject.SaveValue(2, loadingValue)
	stateSinkObject.Save(0, &i.s)
	stateSinkObject.Save(1, &i.sattr)
	stateSinkObject.Save(3, &i.savedUAttr)
	stateSinkObject.Save(4, &i.hostMappable)
}

func (i *inodeFileState) StateLoad(stateSourceObject state.Source) {
	stateSourceObject.LoadWait(0, &i.s)
	stateSourceObject.LoadWait(1, &i.sattr)
	stateSourceObject.Load(3, &i.savedUAttr)
	stateSourceObject.Load(4, &i.hostMappable)
	stateSourceObject.LoadValue(2, new(struct{}), func(y interface{}) { i.loadLoading(y.(struct{})) })
	stateSourceObject.AfterLoad(i.afterLoad)
}

func (o *overrideInfo) StateTypeName() string {
	return "pkg/sentry/fs/gofer.overrideInfo"
}

func (o *overrideInfo) StateFields() []string {
	return []string{
		"dirent",
		"endpoint",
		"inode",
	}
}

func (o *overrideInfo) beforeSave() {}

func (o *overrideInfo) StateSave(stateSinkObject state.Sink) {
	o.beforeSave()
	stateSinkObject.Save(0, &o.dirent)
	stateSinkObject.Save(1, &o.endpoint)
	stateSinkObject.Save(2, &o.inode)
}

func (o *overrideInfo) afterLoad() {}

func (o *overrideInfo) StateLoad(stateSourceObject state.Source) {
	stateSourceObject.Load(0, &o.dirent)
	stateSourceObject.Load(1, &o.endpoint)
	stateSourceObject.Load(2, &o.inode)
}

func (o *overrideMaps) StateTypeName() string {
	return "pkg/sentry/fs/gofer.overrideMaps"
}

func (o *overrideMaps) StateFields() []string {
	return []string{
		"pathMap",
	}
}

func (o *overrideMaps) beforeSave() {}

func (o *overrideMaps) StateSave(stateSinkObject state.Sink) {
	o.beforeSave()
	stateSinkObject.Save(0, &o.pathMap)
}

func (o *overrideMaps) afterLoad() {}

func (o *overrideMaps) StateLoad(stateSourceObject state.Source) {
	stateSourceObject.Load(0, &o.pathMap)
}

func (s *session) StateTypeName() string {
	return "pkg/sentry/fs/gofer.session"
}

func (s *session) StateFields() []string {
	return []string{
		"AtomicRefCount",
		"msize",
		"version",
		"cachePolicy",
		"aname",
		"superBlockFlags",
		"limitHostFDTranslation",
		"overlayfsStaleRead",
		"connID",
		"inodeMappings",
		"mounter",
		"overrides",
	}
}

func (s *session) StateSave(stateSinkObject state.Sink) {
	s.beforeSave()
	stateSinkObject.Save(0, &s.AtomicRefCount)
	stateSinkObject.Save(1, &s.msize)
	stateSinkObject.Save(2, &s.version)
	stateSinkObject.Save(3, &s.cachePolicy)
	stateSinkObject.Save(4, &s.aname)
	stateSinkObject.Save(5, &s.superBlockFlags)
	stateSinkObject.Save(6, &s.limitHostFDTranslation)
	stateSinkObject.Save(7, &s.overlayfsStaleRead)
	stateSinkObject.Save(8, &s.connID)
	stateSinkObject.Save(9, &s.inodeMappings)
	stateSinkObject.Save(10, &s.mounter)
	stateSinkObject.Save(11, &s.overrides)
}

func (s *session) StateLoad(stateSourceObject state.Source) {
	stateSourceObject.Load(0, &s.AtomicRefCount)
	stateSourceObject.LoadWait(1, &s.msize)
	stateSourceObject.LoadWait(2, &s.version)
	stateSourceObject.LoadWait(3, &s.cachePolicy)
	stateSourceObject.LoadWait(4, &s.aname)
	stateSourceObject.LoadWait(5, &s.superBlockFlags)
	stateSourceObject.Load(6, &s.limitHostFDTranslation)
	stateSourceObject.Load(7, &s.overlayfsStaleRead)
	stateSourceObject.LoadWait(8, &s.connID)
	stateSourceObject.LoadWait(9, &s.inodeMappings)
	stateSourceObject.LoadWait(10, &s.mounter)
	stateSourceObject.LoadWait(11, &s.overrides)
	stateSourceObject.AfterLoad(s.afterLoad)
}

func init() {
	state.Register((*fifo)(nil))
	state.Register((*fileOperations)(nil))
	state.Register((*filesystem)(nil))
	state.Register((*inodeOperations)(nil))
	state.Register((*inodeFileState)(nil))
	state.Register((*overrideInfo)(nil))
	state.Register((*overrideMaps)(nil))
	state.Register((*session)(nil))
}
