load("//tools:defs.bzl", "go_library")

package(
    default_applicable_licenses = ["//:license"],
    licenses = ["notice"],
)

go_library(
    name = "prependable",
    srcs = ["prependable.go"],
    importpath = "gvisor.dev/gvisor/pkg/tcpip/prependable",
    visibility = ["//visibility:public"],
)
