load("//tools:defs.bzl", "go_library")

package(
    default_applicable_licenses = [""],
    licenses = ["notice"],
)

go_library(
    name = "prependable",
    srcs = ["prependable.go"],
    visibility = ["//visibility:public"],
)
