load("//tools:defs.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "device",
    srcs = ["device.go"],
    visibility = ["//pkg/sentry:internal"],
    deps = ["//pkg/sentry/device"],
)
