load("//tools:defs.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "argument",
    srcs = [
        "argument.go",
    ],
    visibility = ["//runsc:__subpackages__"],
    deps = ["//runsc/flag"],
)
