load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "marshal",
    srcs = [
        "marshal.go",
    ],
    importpath = "gvisor.dev/gvisor/tools/go_marshal/marshal",
    visibility = [
        "//:sandbox",
    ],
)
