load("//tools:defs.bzl", "go_library")

licenses(["notice"])

go_library(
    name = "marshal",
    srcs = [
        "marshal.go",
    ],
    visibility = [
        "//:sandbox",
    ],
    deps = [
        "//pkg/usermem",
    ],
)
