load("//tools:defs.bzl", "go_library", "go_test")

package(licenses = ["notice"])

go_library(
    name = "spinlock",
    srcs = [
        "spinlock.go",
    ],
    visibility = ["//visibility:public"],
)
