// automatically generated by stateify.

package stateipc

import (
	"context"

	"gvisor.dev/gvisor/pkg/state"
)

func (r *asyncFileClientRefs) StateTypeName() string {
	return "pkg/sentry/state/stateipc.asyncFileClientRefs"
}

func (r *asyncFileClientRefs) StateFields() []string {
	return []string{
		"refCount",
	}
}

func (r *asyncFileClientRefs) beforeSave() {}

// +checklocksignore
func (r *asyncFileClientRefs) StateSave(stateSinkObject state.Sink) {
	r.beforeSave()
	stateSinkObject.Save(0, &r.refCount)
}

// +checklocksignore
func (r *asyncFileClientRefs) StateLoad(ctx context.Context, stateSourceObject state.Source) {
	stateSourceObject.Load(0, &r.refCount)
	stateSourceObject.AfterLoad(func() { r.afterLoad(ctx) })
}

func init() {
	state.Register((*asyncFileClientRefs)(nil))
}
