load("//tools:defs.bzl", "go_library")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//:sandbox"],
    licenses = ["notice"],
)

go_library(
    name = "util",
    srcs = ["util.go"],
    importpath = "gvisor.dev/gvisor/tools/gvisor_k8s_tool/util",
)
