// automatically generated by stateify.

package buffer

import (
	"gvisor.dev/gvisor/pkg/state"
)

func (x *VectorisedView) StateTypeName() string {
	return "pkg/tcpip/buffer.VectorisedView"
}

func (x *VectorisedView) StateFields() []string {
	return []string{
		"views",
		"size",
	}
}

func (x *VectorisedView) beforeSave() {}

func (x *VectorisedView) StateSave(m state.Sink) {
	x.beforeSave()
	m.Save(0, &x.views)
	m.Save(1, &x.size)
}

func (x *VectorisedView) afterLoad() {}

func (x *VectorisedView) StateLoad(m state.Source) {
	m.Load(0, &x.views)
	m.Load(1, &x.size)
}

func init() {
	state.Register((*VectorisedView)(nil))
}
