load("//tools:defs.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "tags",
    srcs = ["tags.go"],
    marshal = False,
    stateify = False,
    visibility = ["//tools:__subpackages__"],
)
