agents:
  queue: release
_templates:
  common: &common
    timeout_in_minutes: 600
    retry:
      automatic:
        - exit_status: -1
          limit: 10
        - exit_status: "*"
          limit: 2

notify:
  - email: "devnull@google.com"  # TODO(b/323401901): Make this not go to /dev/null
    if: build.state == "failed"

env:
  # Force a clean checkout every time to avoid reuse of files between runs.
  BUILDKITE_CLEAN_CHECKOUT: true

steps:
  - <<: *common
    label: ":arrows_counterclockwise: Refresh PGO profiles (x86_64 Systrap)"
    if: build.branch == "master" && build.tag == null
    commands:
      - make ARCH=x86_64 benchmark-refresh-pgo BENCHMARKS_PLATFORMS=systrap
      - '
        if [[ "$(git status --porcelain | wc -l)" -gt 0 ]]; then
          today="$(date +"%Y-%m-%d")" &&
          pgo_branch_name="pgo-update-${today}" &&
          git stash &&
          git pull --rebase=true https://github.com/google/gvisor master &&
          git checkout -b "$pgo_branch_name" &&
          git add runsc/profiles &&
          git status &&
          gh auth login &&
          gh auth setup-git &&
          export GIT_AUTHOR_NAME=gvisor-bot &&
          export GIT_AUTHOR_EMAIL=gvisor-bot@google.com &&
          export GIT_COMMITTER_NAME=gvisor-bot &&
          export GIT_COMMITTER_EMAIL=gvisor-bot@google.com &&
          git commit -m "Update runsc profiles for PGO (profile-guided optimizations), $today." &&
          git push --set-upstream git@github.com:google/gvisor.git "$pgo_branch_name" &&
          gh pr create --title="Update runsc profiles for PGO (profile-guided optimizations), $today." --body="This PR updates the runsc profiles for PGO (profile-guided optimizations)." --label=pgo-update --base=master;
        else
          echo "No changes to runsc profiles." >&2;
        fi
        '
    agents:
      arch: "amd64"
