_templates:
  retry_settings: &retry_settings
    automatic:
      - exit_status: -1
        limit: 10
      - exit_status: "*"
        limit: 2
  common: &common
    timeout_in_minutes: 30
    retry:
      <<: *retry_settings
  source_test: &source_test
    if: build.env("STAGED_BINARIES") == null
  source_test_presubmit: &source_test_presubmit
    if: build.env("STAGED_BINARIES") == null && build.branch != "master"
  source_test_continuous: &source_test_continuous
    if: build.env("STAGED_BINARIES") == null && build.branch == "master"
  platform_specific_agents: &platform_specific_agents {}
  kvm_agents: &kvm_agents {kvm: "true"}
  ubuntu_agents: &ubuntu_agents {os: "ubuntu"}
  docker: &docker
    env:
      BUILDKITE_PIPELINE_INSTALL_RUNTIME: true
  benchmarks: &benchmarks
    timeout_in_minutes: 120
    retry:
      automatic: false
    soft_fail: true
    if: build.branch == "master"
    env:
      # BENCHMARKS_OFFICIAL is set from hooks/pre-command, based
      # on whether this is executing on the master branch.
      BENCHMARKS_DATASET: buildkite
      BENCHMARKS_PROJECT: gvisor-benchmarks
      BENCHMARKS_TABLE: benchmarks
      BENCHMARKS_UPLOAD: true
      BENCHMARKS_PLATFORMS: "kvm systrap"
      BUILDKITE_PIPELINE_INSTALL_RUNTIME: true
    agents:
      <<: *kvm_agents
      <<: *platform_specific_agents
      arch: "amd64"
  netstack_test: &netstack_test
    env:
      PACKAGES: >
        ./pkg/tcpip
        ./pkg/tcpip/adapters/gonet
        ./pkg/tcpip/header
        ./pkg/tcpip/link/channel
        ./pkg/tcpip/network/ipv4
        ./pkg/tcpip/network/ipv6
        ./pkg/tcpip/stack
        ./pkg/tcpip/transport/icmp
        ./pkg/tcpip/transport/tcp
        ./pkg/tcpip/transport/udp
        ./pkg/buffer
        ./pkg/waiter
env:
  # Force a clean checkout every time to avoid reuse of files between runs.
  BUILDKITE_CLEAN_CHECKOUT: true

  # Optional filter for syscall tests.
  SYSCALL_TEST_FILTERS: ''

steps:
  # GPU workflow.
  - <<: *common
    <<: *source_test
    label: ":firefighter: GPU Smoke Tests"
    commands:
      - make sudo TARGETS=//tools/gpu:main ARGS="install --latest" || cat /var/log/nvidia-installer.log
      - make gpu-smoke-tests
      - make sudo TARGETS=//tools/gpu:main ARGS="validate_checksum"
    agents:
      queue: gpu
  - <<: *common
    <<: *source_test_continuous
    label: ":bun: COS Latest Driver Compatibility Test"
    commands:
      - tools/gpu/cos_drivers_test.sh
  - <<: *common
    label: ":screwdriver: GPU Tests"
    commands:
      - make sudo TARGETS=//tools/gpu:main ARGS="install --latest" || cat /var/log/nvidia-installer.log
      - make gpu-all-tests
    agents:
      queue: gpu
  - <<: *common
    label: ":female_supervillain: COS GPU Tests"
    commands:
      - make cos-gpu-all-tests
    agents:
      queue: cos-canary-gpu
  - label: ":fish: CUDA tests"
    # This is its own test rather than being part of the GPU tests,
    # because it takes around 30 minutes to run.
    parallelism: 8
    timeout_in_minutes: 60
    retry:
      <<: *retry_settings
    commands:
      - make sudo TARGETS=//tools/gpu:main ARGS="install --latest" || cat /var/log/nvidia-installer.log
      - make cuda-tests
    agents:
      queue: gpu
  - <<: *common
    label: ":screwdriver: All GPU Drivers Test"
    parallelism: 8
    commands:
      - tools/gpu/all_drivers_test.sh
    agents:
      queue: gpu
