_templates:
  common: &common
    timeout_in_minutes: 30
    retry:
      automatic:
        - exit_status: -1
          limit: 10
        - exit_status: "*"
          limit: 2
steps:
  # Runtime tests.
  - <<: *common
    label: ":java: Java runtime tests"
    command: make java11-runtime-tests
    parallelism: 40
