_templates:
  common: &common
    timeout_in_minutes: 30
    retry:
      automatic:
        - exit_status: -1
          limit: 10
        - exit_status: "*"
          limit: 2
  common_60_tl: &common_60_tl
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: -1
          limit: 10
        - exit_status: "*"
          limit: 2
  source_test: &source_test
    if: build.env("STAGED_BINARIES") == null
  source_test_presubmit: &source_test_presubmit
    if: build.env("STAGED_BINARIES") == null && build.branch != "master"
  source_test_continuous: &source_test_continuous
    if: build.env("STAGED_BINARIES") == null && build.branch == "master"
  platform_specific_agents: &platform_specific_agents {}
  kvm_agents: &kvm_agents {kvm: "true"}
  ubuntu_agents: &ubuntu_agents {os: "ubuntu"}
  docker: &docker
    env:
      BUILDKITE_PIPELINE_INSTALL_RUNTIME: true
  benchmarks: &benchmarks
    timeout_in_minutes: 120
    retry:
      automatic: false
    soft_fail: true
    if: build.branch == "master"
    env:
      # BENCHMARKS_OFFICIAL is set from hooks/pre-command, based
      # on whether this is executing on the master branch.
      BENCHMARKS_DATASET: buildkite
      BENCHMARKS_PROJECT: gvisor-benchmarks
      BENCHMARKS_TABLE: benchmarks
      BENCHMARKS_UPLOAD: true
      BUILDKITE_PIPELINE_INSTALL_RUNTIME: true
    agents:
      <<: *kvm_agents
      <<: *platform_specific_agents
      arch: "amd64"
  netstack_test: &netstack_test
    env:
      PACKAGES: >
        ./pkg/tcpip
        ./pkg/tcpip/adapters/gonet
        ./pkg/tcpip/header
        ./pkg/tcpip/link/channel
        ./pkg/tcpip/network/ipv4
        ./pkg/tcpip/network/ipv6
        ./pkg/tcpip/stack
        ./pkg/tcpip/transport/icmp
        ./pkg/tcpip/transport/tcp
        ./pkg/tcpip/transport/udp
        ./pkg/bufferv2
        ./pkg/waiter
env:
  # Force a clean checkout every time to avoid reuse of files between runs.
  BUILDKITE_CLEAN_CHECKOUT: true

  # Optional filter for syscall tests.
  SYSCALL_TEST_FILTERS: ''

steps:
  - <<: *common
    <<: *docker
    label: ":golang: Go runtime tests"
    command: make go1.20-runtime-tests RUNTIME_ARGS=--directfs
    parallelism: 10
    agents:
      <<: *platform_specific_agents
      <<: *ubuntu_agents
      arch: "amd64"
