package(licenses = ["notice"])  # Apache 2.0

load("//tools/go_stateify:defs.bzl", "go_library")

go_library(
    name = "seqnum",
    srcs = ["seqnum.go"],
    importpath = "gvisor.googlesource.com/gvisor/pkg/tcpip/seqnum",
    visibility = [
        "//visibility:public",
    ],
)
