load("//tools/go_stateify:defs.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "seqnum",
    srcs = ["seqnum.go"],
    importpath = "gvisor.dev/gvisor/pkg/tcpip/seqnum",
    visibility = ["//visibility:public"],
)
