load("//website:defs.bzl", "doc")

package(
    default_visibility = ["//website:__pkg__"],
    licenses = ["notice"],
)

doc(
    name = "docker",
    src = "docker.md",
    category = "User Guide",
    permalink = "/docs/tutorials/docker/",
    subcategory = "Tutorials",
    weight = "21",
)

doc(
    name = "cni",
    src = "cni.md",
    category = "User Guide",
    permalink = "/docs/tutorials/cni/",
    subcategory = "Tutorials",
    weight = "22",
)

doc(
    name = "kubernetes",
    src = "kubernetes.md",
    category = "User Guide",
    data = [
        "add-node-pool.png",
        "node-pool-button.png",
    ],
    permalink = "/docs/tutorials/kubernetes/",
    subcategory = "Tutorials",
    weight = "33",
)
