load("//tools:defs.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "tcp",
    srcs = ["tcp.go"],
    visibility = ["//pkg/tcpip:__subpackages__"],
    deps = [
        "//pkg/tcpip",
    ],
)
