// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/sentry/pgalloc/pgalloc.proto

package pgalloc_metadata_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileRangeProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRangeProto) Reset() {
	*x = FileRangeProto{}
	mi := &file_pkg_sentry_pgalloc_pgalloc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRangeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRangeProto) ProtoMessage() {}

func (x *FileRangeProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sentry_pgalloc_pgalloc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRangeProto.ProtoReflect.Descriptor instead.
func (*FileRangeProto) Descriptor() ([]byte, []int) {
	return file_pkg_sentry_pgalloc_pgalloc_proto_rawDescGZIP(), []int{0}
}

func (x *FileRangeProto) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *FileRangeProto) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

type UnfreeRangeProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Refs          uint64                 `protobuf:"varint,3,opt,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfreeRangeProto) Reset() {
	*x = UnfreeRangeProto{}
	mi := &file_pkg_sentry_pgalloc_pgalloc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfreeRangeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfreeRangeProto) ProtoMessage() {}

func (x *UnfreeRangeProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sentry_pgalloc_pgalloc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfreeRangeProto.ProtoReflect.Descriptor instead.
func (*UnfreeRangeProto) Descriptor() ([]byte, []int) {
	return file_pkg_sentry_pgalloc_pgalloc_proto_rawDescGZIP(), []int{1}
}

func (x *UnfreeRangeProto) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *UnfreeRangeProto) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *UnfreeRangeProto) GetRefs() uint64 {
	if x != nil {
		return x.Refs
	}
	return 0
}

type MemAcctRangeProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Start          uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End            uint64                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Kind           uint32                 `protobuf:"varint,3,opt,name=kind,proto3" json:"kind,omitempty"`
	MemCgId        uint32                 `protobuf:"varint,4,opt,name=mem_cg_id,json=memCgId,proto3" json:"mem_cg_id,omitempty"`
	KnownCommitted bool                   `protobuf:"varint,5,opt,name=known_committed,json=knownCommitted,proto3" json:"known_committed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemAcctRangeProto) Reset() {
	*x = MemAcctRangeProto{}
	mi := &file_pkg_sentry_pgalloc_pgalloc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemAcctRangeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemAcctRangeProto) ProtoMessage() {}

func (x *MemAcctRangeProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sentry_pgalloc_pgalloc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemAcctRangeProto.ProtoReflect.Descriptor instead.
func (*MemAcctRangeProto) Descriptor() ([]byte, []int) {
	return file_pkg_sentry_pgalloc_pgalloc_proto_rawDescGZIP(), []int{2}
}

func (x *MemAcctRangeProto) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *MemAcctRangeProto) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *MemAcctRangeProto) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *MemAcctRangeProto) GetMemCgId() uint32 {
	if x != nil {
		return x.MemCgId
	}
	return 0
}

func (x *MemAcctRangeProto) GetKnownCommitted() bool {
	if x != nil {
		return x.KnownCommitted
	}
	return false
}

type ChunkInfoProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Huge          bool                   `protobuf:"varint,1,opt,name=huge,proto3" json:"huge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkInfoProto) Reset() {
	*x = ChunkInfoProto{}
	mi := &file_pkg_sentry_pgalloc_pgalloc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkInfoProto) ProtoMessage() {}

func (x *ChunkInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sentry_pgalloc_pgalloc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkInfoProto.ProtoReflect.Descriptor instead.
func (*ChunkInfoProto) Descriptor() ([]byte, []int) {
	return file_pkg_sentry_pgalloc_pgalloc_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkInfoProto) GetHuge() bool {
	if x != nil {
		return x.Huge
	}
	return false
}

type MemoryFileMetadataProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Chunks        []*ChunkInfoProto      `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	MemAcct       []*MemAcctRangeProto   `protobuf:"bytes,3,rep,name=mem_acct,json=memAcct,proto3" json:"mem_acct,omitempty"`
	UnfreeSmall   []*UnfreeRangeProto    `protobuf:"bytes,4,rep,name=unfree_small,json=unfreeSmall,proto3" json:"unfree_small,omitempty"`
	UnfreeHuge    []*UnfreeRangeProto    `protobuf:"bytes,5,rep,name=unfree_huge,json=unfreeHuge,proto3" json:"unfree_huge,omitempty"`
	UnwasteSmall  []*FileRangeProto      `protobuf:"bytes,6,rep,name=unwaste_small,json=unwasteSmall,proto3" json:"unwaste_small,omitempty"`
	UnwasteHuge   []*FileRangeProto      `protobuf:"bytes,7,rep,name=unwaste_huge,json=unwasteHuge,proto3" json:"unwaste_huge,omitempty"`
	Subreleased   map[uint64]uint64      `protobuf:"bytes,8,rep,name=subreleased,proto3" json:"subreleased,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryFileMetadataProto) Reset() {
	*x = MemoryFileMetadataProto{}
	mi := &file_pkg_sentry_pgalloc_pgalloc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryFileMetadataProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryFileMetadataProto) ProtoMessage() {}

func (x *MemoryFileMetadataProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sentry_pgalloc_pgalloc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryFileMetadataProto.ProtoReflect.Descriptor instead.
func (*MemoryFileMetadataProto) Descriptor() ([]byte, []int) {
	return file_pkg_sentry_pgalloc_pgalloc_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryFileMetadataProto) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MemoryFileMetadataProto) GetChunks() []*ChunkInfoProto {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *MemoryFileMetadataProto) GetMemAcct() []*MemAcctRangeProto {
	if x != nil {
		return x.MemAcct
	}
	return nil
}

func (x *MemoryFileMetadataProto) GetUnfreeSmall() []*UnfreeRangeProto {
	if x != nil {
		return x.UnfreeSmall
	}
	return nil
}

func (x *MemoryFileMetadataProto) GetUnfreeHuge() []*UnfreeRangeProto {
	if x != nil {
		return x.UnfreeHuge
	}
	return nil
}

func (x *MemoryFileMetadataProto) GetUnwasteSmall() []*FileRangeProto {
	if x != nil {
		return x.UnwasteSmall
	}
	return nil
}

func (x *MemoryFileMetadataProto) GetUnwasteHuge() []*FileRangeProto {
	if x != nil {
		return x.UnwasteHuge
	}
	return nil
}

func (x *MemoryFileMetadataProto) GetSubreleased() map[uint64]uint64 {
	if x != nil {
		return x.Subreleased
	}
	return nil
}

var File_pkg_sentry_pgalloc_pgalloc_proto protoreflect.FileDescriptor

const file_pkg_sentry_pgalloc_pgalloc_proto_rawDesc = "" +
	"\n" +
	" pkg/sentry/pgalloc/pgalloc.proto\x12\x0egvisor.pgalloc\"8\n" +
	"\x0eFileRangeProto\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x04R\x03end\"N\n" +
	"\x10UnfreeRangeProto\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x04R\x03end\x12\x12\n" +
	"\x04refs\x18\x03 \x01(\x04R\x04refs\"\x94\x01\n" +
	"\x11MemAcctRangeProto\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x04R\x03end\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\rR\x04kind\x12\x1a\n" +
	"\tmem_cg_id\x18\x04 \x01(\rR\amemCgId\x12'\n" +
	"\x0fknown_committed\x18\x05 \x01(\bR\x0eknownCommitted\"$\n" +
	"\x0eChunkInfoProto\x12\x12\n" +
	"\x04huge\x18\x01 \x01(\bR\x04huge\"\xd5\x04\n" +
	"\x17MemoryFileMetadataProto\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x126\n" +
	"\x06chunks\x18\x02 \x03(\v2\x1e.gvisor.pgalloc.ChunkInfoProtoR\x06chunks\x12<\n" +
	"\bmem_acct\x18\x03 \x03(\v2!.gvisor.pgalloc.MemAcctRangeProtoR\amemAcct\x12C\n" +
	"\funfree_small\x18\x04 \x03(\v2 .gvisor.pgalloc.UnfreeRangeProtoR\vunfreeSmall\x12A\n" +
	"\vunfree_huge\x18\x05 \x03(\v2 .gvisor.pgalloc.UnfreeRangeProtoR\n" +
	"unfreeHuge\x12C\n" +
	"\runwaste_small\x18\x06 \x03(\v2\x1e.gvisor.pgalloc.FileRangeProtoR\funwasteSmall\x12A\n" +
	"\funwaste_huge\x18\a \x03(\v2\x1e.gvisor.pgalloc.FileRangeProtoR\vunwasteHuge\x12Z\n" +
	"\vsubreleased\x18\b \x03(\v28.gvisor.pgalloc.MemoryFileMetadataProto.SubreleasedEntryR\vsubreleased\x1a>\n" +
	"\x10SubreleasedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01b\x06proto3"

var (
	file_pkg_sentry_pgalloc_pgalloc_proto_rawDescOnce sync.Once
	file_pkg_sentry_pgalloc_pgalloc_proto_rawDescData []byte
)

func file_pkg_sentry_pgalloc_pgalloc_proto_rawDescGZIP() []byte {
	file_pkg_sentry_pgalloc_pgalloc_proto_rawDescOnce.Do(func() {
		file_pkg_sentry_pgalloc_pgalloc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_sentry_pgalloc_pgalloc_proto_rawDesc), len(file_pkg_sentry_pgalloc_pgalloc_proto_rawDesc)))
	})
	return file_pkg_sentry_pgalloc_pgalloc_proto_rawDescData
}

var file_pkg_sentry_pgalloc_pgalloc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_sentry_pgalloc_pgalloc_proto_goTypes = []any{
	(*FileRangeProto)(nil),          // 0: gvisor.pgalloc.FileRangeProto
	(*UnfreeRangeProto)(nil),        // 1: gvisor.pgalloc.UnfreeRangeProto
	(*MemAcctRangeProto)(nil),       // 2: gvisor.pgalloc.MemAcctRangeProto
	(*ChunkInfoProto)(nil),          // 3: gvisor.pgalloc.ChunkInfoProto
	(*MemoryFileMetadataProto)(nil), // 4: gvisor.pgalloc.MemoryFileMetadataProto
	nil,                             // 5: gvisor.pgalloc.MemoryFileMetadataProto.SubreleasedEntry
}
var file_pkg_sentry_pgalloc_pgalloc_proto_depIdxs = []int32{
	3, // 0: gvisor.pgalloc.MemoryFileMetadataProto.chunks:type_name -> gvisor.pgalloc.ChunkInfoProto
	2, // 1: gvisor.pgalloc.MemoryFileMetadataProto.mem_acct:type_name -> gvisor.pgalloc.MemAcctRangeProto
	1, // 2: gvisor.pgalloc.MemoryFileMetadataProto.unfree_small:type_name -> gvisor.pgalloc.UnfreeRangeProto
	1, // 3: gvisor.pgalloc.MemoryFileMetadataProto.unfree_huge:type_name -> gvisor.pgalloc.UnfreeRangeProto
	0, // 4: gvisor.pgalloc.MemoryFileMetadataProto.unwaste_small:type_name -> gvisor.pgalloc.FileRangeProto
	0, // 5: gvisor.pgalloc.MemoryFileMetadataProto.unwaste_huge:type_name -> gvisor.pgalloc.FileRangeProto
	5, // 6: gvisor.pgalloc.MemoryFileMetadataProto.subreleased:type_name -> gvisor.pgalloc.MemoryFileMetadataProto.SubreleasedEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_sentry_pgalloc_pgalloc_proto_init() }
func file_pkg_sentry_pgalloc_pgalloc_proto_init() {
	if File_pkg_sentry_pgalloc_pgalloc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_sentry_pgalloc_pgalloc_proto_rawDesc), len(file_pkg_sentry_pgalloc_pgalloc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_sentry_pgalloc_pgalloc_proto_goTypes,
		DependencyIndexes: file_pkg_sentry_pgalloc_pgalloc_proto_depIdxs,
		MessageInfos:      file_pkg_sentry_pgalloc_pgalloc_proto_msgTypes,
	}.Build()
	File_pkg_sentry_pgalloc_pgalloc_proto = out.File
	file_pkg_sentry_pgalloc_pgalloc_proto_goTypes = nil
	file_pkg_sentry_pgalloc_pgalloc_proto_depIdxs = nil
}
