load("//tools:defs.bzl", "go_library")

package(default_applicable_licenses = ["//:license"])

licenses(["notice"])

go_library(
    name = "rdma",
    srcs = [
        "collect.go",
        "snapshot.go",
    ],
    visibility = ["//visibility:public"],
)
