load("//tools:defs.bzl", "cc_binary")

package(licenses = ["notice"])

cc_binary(
    name = "workload",
    testonly = 1,
    srcs = [
        "workload.cc",
    ],
    visibility = ["//test/trace:__pkg__"],
    deps = [
    ],
)
