load("//tools:defs.bzl", "go_library")

package(
    default_visibility = ["//test/packetimpact:__subpackages__"],
    licenses = ["notice"],
)

go_library(
    name = "testing",
    testonly = True,
    srcs = ["testing.go"],
)
