// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/sentry/control/tpu_control.proto

package tpu_control_proto_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlAction int32

const (
	ControlAction_ACTION_UNSPECIFIED ControlAction = 0
	ControlAction_ACTION_LOCK        ControlAction = 1
	ControlAction_ACTION_CHECKPOINT  ControlAction = 2
	ControlAction_ACTION_RESTORE     ControlAction = 3
	ControlAction_ACTION_UNLOCK      ControlAction = 4
	ControlAction_ACTION_GETSTATE    ControlAction = 5
)

// Enum value maps for ControlAction.
var (
	ControlAction_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_LOCK",
		2: "ACTION_CHECKPOINT",
		3: "ACTION_RESTORE",
		4: "ACTION_UNLOCK",
		5: "ACTION_GETSTATE",
	}
	ControlAction_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_LOCK":        1,
		"ACTION_CHECKPOINT":  2,
		"ACTION_RESTORE":     3,
		"ACTION_UNLOCK":      4,
		"ACTION_GETSTATE":    5,
	}
)

func (x ControlAction) Enum() *ControlAction {
	p := new(ControlAction)
	*p = x
	return p
}

func (x ControlAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlAction) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_sentry_control_tpu_control_proto_enumTypes[0].Descriptor()
}

func (ControlAction) Type() protoreflect.EnumType {
	return &file_pkg_sentry_control_tpu_control_proto_enumTypes[0]
}

func (x ControlAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type RuntimeState int32

const (
	RuntimeState_STATE_UNSPECIFIED RuntimeState = 0
	RuntimeState_STATE_RUNNING     RuntimeState = 1
	RuntimeState_STATE_LOCKED      RuntimeState = 2
	RuntimeState_STATE_DETACHED    RuntimeState = 3
	RuntimeState_STATE_RESTORING   RuntimeState = 4
	RuntimeState_STATE_FAULTED     RuntimeState = 5
)

// Enum value maps for RuntimeState.
var (
	RuntimeState_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_RUNNING",
		2: "STATE_LOCKED",
		3: "STATE_DETACHED",
		4: "STATE_RESTORING",
		5: "STATE_FAULTED",
	}
	RuntimeState_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_RUNNING":     1,
		"STATE_LOCKED":      2,
		"STATE_DETACHED":    3,
		"STATE_RESTORING":   4,
		"STATE_FAULTED":     5,
	}
)

func (x RuntimeState) Enum() *RuntimeState {
	p := new(RuntimeState)
	*p = x
	return p
}

func (x RuntimeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_sentry_control_tpu_control_proto_enumTypes[1].Descriptor()
}

func (RuntimeState) Type() protoreflect.EnumType {
	return &file_pkg_sentry_control_tpu_control_proto_enumTypes[1]
}

func (x RuntimeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type TpuTopology struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChipArchitecture *string                `protobuf:"bytes,1,opt,name=chip_architecture,json=chipArchitecture"`
	xxx_hidden_NumChips         int32                  `protobuf:"varint,2,opt,name=num_chips,json=numChips"`
	xxx_hidden_MeshShape        *string                `protobuf:"bytes,3,opt,name=mesh_shape,json=meshShape"`
	xxx_hidden_PjrtVersion      *string                `protobuf:"bytes,4,opt,name=pjrt_version,json=pjrtVersion"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *TpuTopology) Reset() {
	*x = TpuTopology{}
	mi := &file_pkg_sentry_control_tpu_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TpuTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TpuTopology) ProtoMessage() {}

func (x *TpuTopology) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sentry_control_tpu_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TpuTopology) GetChipArchitecture() string {
	if x != nil {
		if x.xxx_hidden_ChipArchitecture != nil {
			return *x.xxx_hidden_ChipArchitecture
		}
		return ""
	}
	return ""
}

func (x *TpuTopology) GetNumChips() int32 {
	if x != nil {
		return x.xxx_hidden_NumChips
	}
	return 0
}

func (x *TpuTopology) GetMeshShape() string {
	if x != nil {
		if x.xxx_hidden_MeshShape != nil {
			return *x.xxx_hidden_MeshShape
		}
		return ""
	}
	return ""
}

func (x *TpuTopology) GetPjrtVersion() string {
	if x != nil {
		if x.xxx_hidden_PjrtVersion != nil {
			return *x.xxx_hidden_PjrtVersion
		}
		return ""
	}
	return ""
}

func (x *TpuTopology) SetChipArchitecture(v string) {
	x.xxx_hidden_ChipArchitecture = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *TpuTopology) SetNumChips(v int32) {
	x.xxx_hidden_NumChips = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *TpuTopology) SetMeshShape(v string) {
	x.xxx_hidden_MeshShape = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *TpuTopology) SetPjrtVersion(v string) {
	x.xxx_hidden_PjrtVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *TpuTopology) HasChipArchitecture() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TpuTopology) HasNumChips() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TpuTopology) HasMeshShape() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TpuTopology) HasPjrtVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TpuTopology) ClearChipArchitecture() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ChipArchitecture = nil
}

func (x *TpuTopology) ClearNumChips() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NumChips = 0
}

func (x *TpuTopology) ClearMeshShape() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MeshShape = nil
}

func (x *TpuTopology) ClearPjrtVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_PjrtVersion = nil
}

type TpuTopology_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ChipArchitecture *string
	NumChips         *int32
	MeshShape        *string
	PjrtVersion      *string
}

func (b0 TpuTopology_builder) Build() *TpuTopology {
	m0 := &TpuTopology{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ChipArchitecture != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_ChipArchitecture = b.ChipArchitecture
	}
	if b.NumChips != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_NumChips = *b.NumChips
	}
	if b.MeshShape != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_MeshShape = b.MeshShape
	}
	if b.PjrtVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_PjrtVersion = b.PjrtVersion
	}
	return m0
}

type ControlRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Action           ControlAction          `protobuf:"varint,1,opt,name=action,enum=cloud_gvisor.tpu.ControlAction"`
	xxx_hidden_TimeoutSecs      int32                  `protobuf:"varint,2,opt,name=timeout_secs,json=timeoutSecs"`
	xxx_hidden_ExpectedTopology *TpuTopology           `protobuf:"bytes,3,opt,name=expected_topology,json=expectedTopology"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_pkg_sentry_control_tpu_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sentry_control_tpu_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ControlRequest) GetAction() ControlAction {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Action
		}
	}
	return ControlAction_ACTION_UNSPECIFIED
}

func (x *ControlRequest) GetTimeoutSecs() int32 {
	if x != nil {
		return x.xxx_hidden_TimeoutSecs
	}
	return 0
}

func (x *ControlRequest) GetExpectedTopology() *TpuTopology {
	if x != nil {
		return x.xxx_hidden_ExpectedTopology
	}
	return nil
}

func (x *ControlRequest) SetAction(v ControlAction) {
	x.xxx_hidden_Action = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ControlRequest) SetTimeoutSecs(v int32) {
	x.xxx_hidden_TimeoutSecs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ControlRequest) SetExpectedTopology(v *TpuTopology) {
	x.xxx_hidden_ExpectedTopology = v
}

func (x *ControlRequest) HasAction() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ControlRequest) HasTimeoutSecs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ControlRequest) HasExpectedTopology() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpectedTopology != nil
}

func (x *ControlRequest) ClearAction() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Action = ControlAction_ACTION_UNSPECIFIED
}

func (x *ControlRequest) ClearTimeoutSecs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TimeoutSecs = 0
}

func (x *ControlRequest) ClearExpectedTopology() {
	x.xxx_hidden_ExpectedTopology = nil
}

type ControlRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Action           *ControlAction
	TimeoutSecs      *int32
	ExpectedTopology *TpuTopology
}

func (b0 ControlRequest_builder) Build() *ControlRequest {
	m0 := &ControlRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Action != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Action = *b.Action
	}
	if b.TimeoutSecs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_TimeoutSecs = *b.TimeoutSecs
	}
	x.xxx_hidden_ExpectedTopology = b.ExpectedTopology
	return m0
}

type ControlResponse struct {
	state                     protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Success        bool                        `protobuf:"varint,1,opt,name=success"`
	xxx_hidden_CurrentState   RuntimeState                `protobuf:"varint,2,opt,name=current_state,json=currentState,enum=cloud_gvisor.tpu.RuntimeState"`
	xxx_hidden_ErrorMessage   *string                     `protobuf:"bytes,3,opt,name=error_message,json=errorMessage"`
	xxx_hidden_ActiveTopology *TpuTopology                `protobuf:"bytes,4,opt,name=active_topology,json=activeTopology"`
	xxx_hidden_Telemetry      isControlResponse_Telemetry `protobuf_oneof:"telemetry"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_pkg_sentry_control_tpu_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sentry_control_tpu_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ControlResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *ControlResponse) GetCurrentState() RuntimeState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_CurrentState
		}
	}
	return RuntimeState_STATE_UNSPECIFIED
}

func (x *ControlResponse) GetErrorMessage() string {
	if x != nil {
		if x.xxx_hidden_ErrorMessage != nil {
			return *x.xxx_hidden_ErrorMessage
		}
		return ""
	}
	return ""
}

func (x *ControlResponse) GetActiveTopology() *TpuTopology {
	if x != nil {
		return x.xxx_hidden_ActiveTopology
	}
	return nil
}

func (x *ControlResponse) GetCheckpointStats() *CheckpointTelemetry {
	if x != nil {
		if x, ok := x.xxx_hidden_Telemetry.(*controlResponse_CheckpointStats); ok {
			return x.CheckpointStats
		}
	}
	return nil
}

func (x *ControlResponse) GetRestoreStats() *RestoreTelemetry {
	if x != nil {
		if x, ok := x.xxx_hidden_Telemetry.(*controlResponse_RestoreStats); ok {
			return x.RestoreStats
		}
	}
	return nil
}

func (x *ControlResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *ControlResponse) SetCurrentState(v RuntimeState) {
	x.xxx_hidden_CurrentState = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *ControlResponse) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *ControlResponse) SetActiveTopology(v *TpuTopology) {
	x.xxx_hidden_ActiveTopology = v
}

func (x *ControlResponse) SetCheckpointStats(v *CheckpointTelemetry) {
	if v == nil {
		x.xxx_hidden_Telemetry = nil
		return
	}
	x.xxx_hidden_Telemetry = &controlResponse_CheckpointStats{v}
}

func (x *ControlResponse) SetRestoreStats(v *RestoreTelemetry) {
	if v == nil {
		x.xxx_hidden_Telemetry = nil
		return
	}
	x.xxx_hidden_Telemetry = &controlResponse_RestoreStats{v}
}

func (x *ControlResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ControlResponse) HasCurrentState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ControlResponse) HasErrorMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ControlResponse) HasActiveTopology() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ActiveTopology != nil
}

func (x *ControlResponse) HasTelemetry() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Telemetry != nil
}

func (x *ControlResponse) HasCheckpointStats() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Telemetry.(*controlResponse_CheckpointStats)
	return ok
}

func (x *ControlResponse) HasRestoreStats() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Telemetry.(*controlResponse_RestoreStats)
	return ok
}

func (x *ControlResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

func (x *ControlResponse) ClearCurrentState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CurrentState = RuntimeState_STATE_UNSPECIFIED
}

func (x *ControlResponse) ClearErrorMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ErrorMessage = nil
}

func (x *ControlResponse) ClearActiveTopology() {
	x.xxx_hidden_ActiveTopology = nil
}

func (x *ControlResponse) ClearTelemetry() {
	x.xxx_hidden_Telemetry = nil
}

func (x *ControlResponse) ClearCheckpointStats() {
	if _, ok := x.xxx_hidden_Telemetry.(*controlResponse_CheckpointStats); ok {
		x.xxx_hidden_Telemetry = nil
	}
}

func (x *ControlResponse) ClearRestoreStats() {
	if _, ok := x.xxx_hidden_Telemetry.(*controlResponse_RestoreStats); ok {
		x.xxx_hidden_Telemetry = nil
	}
}

const ControlResponse_Telemetry_not_set_case case_ControlResponse_Telemetry = 0
const ControlResponse_CheckpointStats_case case_ControlResponse_Telemetry = 5
const ControlResponse_RestoreStats_case case_ControlResponse_Telemetry = 6

func (x *ControlResponse) WhichTelemetry() case_ControlResponse_Telemetry {
	if x == nil {
		return ControlResponse_Telemetry_not_set_case
	}
	switch x.xxx_hidden_Telemetry.(type) {
	case *controlResponse_CheckpointStats:
		return ControlResponse_CheckpointStats_case
	case *controlResponse_RestoreStats:
		return ControlResponse_RestoreStats_case
	default:
		return ControlResponse_Telemetry_not_set_case
	}
}

type ControlResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success        *bool
	CurrentState   *RuntimeState
	ErrorMessage   *string
	ActiveTopology *TpuTopology
	// Fields of oneof xxx_hidden_Telemetry:
	CheckpointStats *CheckpointTelemetry
	RestoreStats    *RestoreTelemetry
	// -- end of xxx_hidden_Telemetry
}

func (b0 ControlResponse_builder) Build() *ControlResponse {
	m0 := &ControlResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Success = *b.Success
	}
	if b.CurrentState != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_CurrentState = *b.CurrentState
	}
	if b.ErrorMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_ErrorMessage = b.ErrorMessage
	}
	x.xxx_hidden_ActiveTopology = b.ActiveTopology
	if b.CheckpointStats != nil {
		x.xxx_hidden_Telemetry = &controlResponse_CheckpointStats{b.CheckpointStats}
	}
	if b.RestoreStats != nil {
		x.xxx_hidden_Telemetry = &controlResponse_RestoreStats{b.RestoreStats}
	}
	return m0
}

type case_ControlResponse_Telemetry protoreflect.FieldNumber

func (x case_ControlResponse_Telemetry) String() string {
	md := file_pkg_sentry_control_tpu_control_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isControlResponse_Telemetry interface {
	isControlResponse_Telemetry()
}

type controlResponse_CheckpointStats struct {
	CheckpointStats *CheckpointTelemetry `protobuf:"bytes,5,opt,name=checkpoint_stats,json=checkpointStats,oneof"`
}

type controlResponse_RestoreStats struct {
	RestoreStats *RestoreTelemetry `protobuf:"bytes,6,opt,name=restore_stats,json=restoreStats,oneof"`
}

func (*controlResponse_CheckpointStats) isControlResponse_Telemetry() {}

func (*controlResponse_RestoreStats) isControlResponse_Telemetry() {}

type CheckpointTelemetry struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointTelemetry) Reset() {
	*x = CheckpointTelemetry{}
	mi := &file_pkg_sentry_control_tpu_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointTelemetry) ProtoMessage() {}

func (x *CheckpointTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sentry_control_tpu_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CheckpointTelemetry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CheckpointTelemetry_builder) Build() *CheckpointTelemetry {
	m0 := &CheckpointTelemetry{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RestoreTelemetry struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreTelemetry) Reset() {
	*x = RestoreTelemetry{}
	mi := &file_pkg_sentry_control_tpu_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreTelemetry) ProtoMessage() {}

func (x *RestoreTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sentry_control_tpu_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RestoreTelemetry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RestoreTelemetry_builder) Build() *RestoreTelemetry {
	m0 := &RestoreTelemetry{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_pkg_sentry_control_tpu_control_proto protoreflect.FileDescriptor

const file_pkg_sentry_control_tpu_control_proto_rawDesc = "" +
	"\n" +
	"$pkg/sentry/control/tpu_control.proto\x12\x10cloud_gvisor.tpu\"\x99\x01\n" +
	"\vTpuTopology\x12+\n" +
	"\x11chip_architecture\x18\x01 \x01(\tR\x10chipArchitecture\x12\x1b\n" +
	"\tnum_chips\x18\x02 \x01(\x05R\bnumChips\x12\x1d\n" +
	"\n" +
	"mesh_shape\x18\x03 \x01(\tR\tmeshShape\x12!\n" +
	"\fpjrt_version\x18\x04 \x01(\tR\vpjrtVersion\"\xb8\x01\n" +
	"\x0eControlRequest\x127\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1f.cloud_gvisor.tpu.ControlActionR\x06action\x12!\n" +
	"\ftimeout_secs\x18\x02 \x01(\x05R\vtimeoutSecs\x12J\n" +
	"\x11expected_topology\x18\x03 \x01(\v2\x1d.cloud_gvisor.tpu.TpuTopologyR\x10expectedTopology\"\x89\x03\n" +
	"\x0fControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12C\n" +
	"\rcurrent_state\x18\x02 \x01(\x0e2\x1e.cloud_gvisor.tpu.RuntimeStateR\fcurrentState\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12F\n" +
	"\x0factive_topology\x18\x04 \x01(\v2\x1d.cloud_gvisor.tpu.TpuTopologyR\x0eactiveTopology\x12R\n" +
	"\x10checkpoint_stats\x18\x05 \x01(\v2%.cloud_gvisor.tpu.CheckpointTelemetryH\x00R\x0fcheckpointStats\x12I\n" +
	"\rrestore_stats\x18\x06 \x01(\v2\".cloud_gvisor.tpu.RestoreTelemetryH\x00R\frestoreStatsB\v\n" +
	"\ttelemetry\"\x15\n" +
	"\x13CheckpointTelemetry\"\x12\n" +
	"\x10RestoreTelemetry*\x8b\x01\n" +
	"\rControlAction\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vACTION_LOCK\x10\x01\x12\x15\n" +
	"\x11ACTION_CHECKPOINT\x10\x02\x12\x12\n" +
	"\x0eACTION_RESTORE\x10\x03\x12\x11\n" +
	"\rACTION_UNLOCK\x10\x04\x12\x13\n" +
	"\x0fACTION_GETSTATE\x10\x05*\x86\x01\n" +
	"\fRuntimeState\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x01\x12\x10\n" +
	"\fSTATE_LOCKED\x10\x02\x12\x12\n" +
	"\x0eSTATE_DETACHED\x10\x03\x12\x13\n" +
	"\x0fSTATE_RESTORING\x10\x04\x12\x11\n" +
	"\rSTATE_FAULTED\x10\x05b\beditionsp\xe9\a"

var file_pkg_sentry_control_tpu_control_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_sentry_control_tpu_control_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_sentry_control_tpu_control_proto_goTypes = []any{
	(ControlAction)(0),          // 0: cloud_gvisor.tpu.ControlAction
	(RuntimeState)(0),           // 1: cloud_gvisor.tpu.RuntimeState
	(*TpuTopology)(nil),         // 2: cloud_gvisor.tpu.TpuTopology
	(*ControlRequest)(nil),      // 3: cloud_gvisor.tpu.ControlRequest
	(*ControlResponse)(nil),     // 4: cloud_gvisor.tpu.ControlResponse
	(*CheckpointTelemetry)(nil), // 5: cloud_gvisor.tpu.CheckpointTelemetry
	(*RestoreTelemetry)(nil),    // 6: cloud_gvisor.tpu.RestoreTelemetry
}
var file_pkg_sentry_control_tpu_control_proto_depIdxs = []int32{
	0, // 0: cloud_gvisor.tpu.ControlRequest.action:type_name -> cloud_gvisor.tpu.ControlAction
	2, // 1: cloud_gvisor.tpu.ControlRequest.expected_topology:type_name -> cloud_gvisor.tpu.TpuTopology
	1, // 2: cloud_gvisor.tpu.ControlResponse.current_state:type_name -> cloud_gvisor.tpu.RuntimeState
	2, // 3: cloud_gvisor.tpu.ControlResponse.active_topology:type_name -> cloud_gvisor.tpu.TpuTopology
	5, // 4: cloud_gvisor.tpu.ControlResponse.checkpoint_stats:type_name -> cloud_gvisor.tpu.CheckpointTelemetry
	6, // 5: cloud_gvisor.tpu.ControlResponse.restore_stats:type_name -> cloud_gvisor.tpu.RestoreTelemetry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_sentry_control_tpu_control_proto_init() }
func file_pkg_sentry_control_tpu_control_proto_init() {
	if File_pkg_sentry_control_tpu_control_proto != nil {
		return
	}
	file_pkg_sentry_control_tpu_control_proto_msgTypes[2].OneofWrappers = []any{
		(*controlResponse_CheckpointStats)(nil),
		(*controlResponse_RestoreStats)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_sentry_control_tpu_control_proto_rawDesc), len(file_pkg_sentry_control_tpu_control_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_sentry_control_tpu_control_proto_goTypes,
		DependencyIndexes: file_pkg_sentry_control_tpu_control_proto_depIdxs,
		EnumInfos:         file_pkg_sentry_control_tpu_control_proto_enumTypes,
		MessageInfos:      file_pkg_sentry_control_tpu_control_proto_msgTypes,
	}.Build()
	File_pkg_sentry_control_tpu_control_proto = out.File
	file_pkg_sentry_control_tpu_control_proto_goTypes = nil
	file_pkg_sentry_control_tpu_control_proto_depIdxs = nil
}
