package(licenses = ["notice"])  # Apache 2.0

load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "tun",
    srcs = ["tun_unsafe.go"],
    importpath = "gvisor.googlesource.com/gvisor/pkg/tcpip/link/tun",
    visibility = [
        "//visibility:public",
    ],
)
