// automatically generated by stateify.

// +build arm64
// +build arm64
// +build arm64

package linux

import (
	"gvisor.dev/gvisor/pkg/state"
)

func (x *PtraceRegs) StateTypeName() string {
	return "pkg/abi/linux.PtraceRegs"
}

func (x *PtraceRegs) StateFields() []string {
	return []string{
		"Regs",
		"Sp",
		"Pc",
		"Pstate",
	}
}

func (x *PtraceRegs) beforeSave() {}

func (x *PtraceRegs) StateSave(m state.Sink) {
	x.beforeSave()
	m.Save(0, &x.Regs)
	m.Save(1, &x.Sp)
	m.Save(2, &x.Pc)
	m.Save(3, &x.Pstate)
}

func (x *PtraceRegs) afterLoad() {}

func (x *PtraceRegs) StateLoad(m state.Source) {
	m.Load(0, &x.Regs)
	m.Load(1, &x.Sp)
	m.Load(2, &x.Pc)
	m.Load(3, &x.Pstate)
}

func init() {
	state.Register((*PtraceRegs)(nil))
}
