load("//tools:defs.bzl", "proto_library")

package(
    default_applicable_licenses = ["//:license"],
    licenses = ["notice"],
)

proto_library(
    name = "sandbox_options",
    srcs = ["sandbox_options.proto"],
)
