// Copyright 2026 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package gvisor.fscheckpoint;

message ResourceID {
  string container_name = 1;
  string path = 2;
}

message MemoryFile {
  ResourceID resource_id = 1;
  uint64 pages_metadata_start = 2;
  uint64 pages_metadata_end = 3;
  uint64 pages_start = 4;
}

message Tmpfs {
  ResourceID resource_id = 1;
  uint64 tar_start = 2;
  uint64 tar_end = 3;
}

message Manifest {
  uint64 version = 1;
  string runsc_version = 2;
  uint64 page_size = 3;
  // TODO: NOLINT - Currently this must match during restore. Removing this
  // requirement requires fixing an endianness for
  // tmpfs.fsckptRegularFileSegment.
  string endian = 4;
  repeated MemoryFile memory_files = 5;
  repeated Tmpfs tmpfs = 6;
}
