# Control config in the Sentry.

load("//tools:defs.bzl", "proto_library")

package(licenses = ["notice"])

proto_library(
    name = "control",
    srcs = ["control.proto"],
    visibility = ["//visibility:public"],
)
