load("//tools:defs.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "abi",
    srcs = [
        "abi.go",
        "abi_linux.go",
        "flag.go",
    ],
    visibility = ["//:sandbox"],
)
