load("//website:defs.bzl", "doc")

package(
    default_visibility = ["//website:__pkg__"],
    licenses = ["notice"],
)

doc(
    name = "index",
    src = "README.md",
    permalink = "/docs/",
    weight = "0",
)

doc(
    name = "roadmap",
    src = "roadmap.md",
    category = "Project",
    permalink = "/roadmap/",
    weight = "10",
)

doc(
    name = "basics",
    src = "basics.md",
    category = "Project",
    permalink = "/docs/basics/",
)

doc(
    name = "community",
    src = "community.md",
    category = "Project",
    permalink = "/community/",
    subcategory = "Community",
    weight = "95",
)
