load("//website:defs.bzl", "doc")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//website:__pkg__"],
    licenses = ["notice"],
)

doc(
    name = "go",
    src = "go.md",
    category = "SDK/API Reference",
    permalink = "/docs/sdk/go/",
    subcategory = "Go",
    weight = "10",
)

doc(
    name = "quickstart",
    src = "quickstart.md",
    category = "SDK/API Reference",
    permalink = "/docs/sdk/go/quickstart/",
    subcategory = "Go",
    weight = "20",
)
