// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.2
// source: pkg/sentry/socket/netstack/events.proto

package events_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SentryTcpListenEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          *int32                 `protobuf:"varint,1,opt,name=port,proto3,oneof" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentryTcpListenEvent) Reset() {
	*x = SentryTcpListenEvent{}
	mi := &file_pkg_sentry_socket_netstack_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentryTcpListenEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentryTcpListenEvent) ProtoMessage() {}

func (x *SentryTcpListenEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sentry_socket_netstack_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentryTcpListenEvent.ProtoReflect.Descriptor instead.
func (*SentryTcpListenEvent) Descriptor() ([]byte, []int) {
	return file_pkg_sentry_socket_netstack_events_proto_rawDescGZIP(), []int{0}
}

func (x *SentryTcpListenEvent) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

var File_pkg_sentry_socket_netstack_events_proto protoreflect.FileDescriptor

const file_pkg_sentry_socket_netstack_events_proto_rawDesc = "" +
	"\n" +
	"'pkg/sentry/socket/netstack/events.proto\x12\x06gvisor\"8\n" +
	"\x14SentryTcpListenEvent\x12\x17\n" +
	"\x04port\x18\x01 \x01(\x05H\x00R\x04port\x88\x01\x01B\a\n" +
	"\x05_portb\x06proto3"

var (
	file_pkg_sentry_socket_netstack_events_proto_rawDescOnce sync.Once
	file_pkg_sentry_socket_netstack_events_proto_rawDescData []byte
)

func file_pkg_sentry_socket_netstack_events_proto_rawDescGZIP() []byte {
	file_pkg_sentry_socket_netstack_events_proto_rawDescOnce.Do(func() {
		file_pkg_sentry_socket_netstack_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_sentry_socket_netstack_events_proto_rawDesc), len(file_pkg_sentry_socket_netstack_events_proto_rawDesc)))
	})
	return file_pkg_sentry_socket_netstack_events_proto_rawDescData
}

var file_pkg_sentry_socket_netstack_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_sentry_socket_netstack_events_proto_goTypes = []any{
	(*SentryTcpListenEvent)(nil), // 0: gvisor.SentryTcpListenEvent
}
var file_pkg_sentry_socket_netstack_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_sentry_socket_netstack_events_proto_init() }
func file_pkg_sentry_socket_netstack_events_proto_init() {
	if File_pkg_sentry_socket_netstack_events_proto != nil {
		return
	}
	file_pkg_sentry_socket_netstack_events_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_sentry_socket_netstack_events_proto_rawDesc), len(file_pkg_sentry_socket_netstack_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_sentry_socket_netstack_events_proto_goTypes,
		DependencyIndexes: file_pkg_sentry_socket_netstack_events_proto_depIdxs,
		MessageInfos:      file_pkg_sentry_socket_netstack_events_proto_msgTypes,
	}.Build()
	File_pkg_sentry_socket_netstack_events_proto = out.File
	file_pkg_sentry_socket_netstack_events_proto_goTypes = nil
	file_pkg_sentry_socket_netstack_events_proto_depIdxs = nil
}
