load("//website:defs.bzl", "doc")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//website:__pkg__"],
    licenses = ["notice"],
)

doc(
    name = "bwrap",
    src = "bwrap.md",
    category = "User Guide",
    permalink = "/docs/user_guide/personalities/bwrap/",
    subcategory = "Personalities",
    weight = "10",
)
