load("//tools:defs.bzl", "proto_library")

licenses(["notice"])

package(default_visibility = ["//:sandbox"])

proto_library(
    name = "points",
    srcs = [
        "common.proto",
        "container.proto",
        "sentry.proto",
        "syscall.proto",
    ],
)
