// automatically generated by stateify.

package socket

import (
	"gvisor.dev/gvisor/pkg/state"
)

func (x *SendReceiveTimeout) beforeSave() {}
func (x *SendReceiveTimeout) save(m state.Map) {
	x.beforeSave()
	m.Save("send", &x.send)
	m.Save("recv", &x.recv)
}

func (x *SendReceiveTimeout) afterLoad() {}
func (x *SendReceiveTimeout) load(m state.Map) {
	m.Load("send", &x.send)
	m.Load("recv", &x.recv)
}

func init() {
	state.Register("socket.SendReceiveTimeout", (*SendReceiveTimeout)(nil), state.Fns{Save: (*SendReceiveTimeout).save, Load: (*SendReceiveTimeout).load})
}
