load("//tools:defs.bzl", "go_library")

package(
    default_applicable_licenses = ["//:license"],
    licenses = ["notice"],
)

go_library(
    name = "hostlayoutcheck",
    srcs = ["hostlayoutcheck.go"],
    importpath = "gvisor.dev/gvisor/tools/go_hostlayout/hostlayoutcheck",
    visibility = ["//visibility:public"],
)
