load("//tools:defs.bzl", "go_library")

package(
    default_applicable_licenses = [""],
    licenses = ["notice"],
)

go_library(
    name = "test",
    testonly = 1,
    srcs = ["test_unsafe.go"],
)
