load("//tools:defs.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "securejoin",
    srcs = [
        "join.go",
        "vfs.go",
    ],
    visibility = ["//runsc:__subpackages__"],
    deps = [
        
    ],
)

