load("//test/runner:defs.bzl", "syscall_test")

package(licenses = ["notice"])

syscall_test(
    test = "//test/fuse/linux:stat_test",
    vfs2 = "True",
    fuse = "True",
)

syscall_test(
    test = "//test/fuse/linux:mknod_test",
    vfs2 = "True",
    fuse = "True",
)

syscall_test(
    test = "//test/fuse/linux:open_test",
    vfs2 = "True",
    fuse = "True",
)

syscall_test(
    test = "//test/fuse/linux:readdir_test",
    vfs2 = "True",
    fuse = "True",
)

syscall_test(
    test = "//test/fuse/linux:mkdir_test",
    vfs2 = "True",
    fuse = "True",
)

syscall_test(
    test = "//test/fuse/linux:rmdir_test",
    vfs2 = "True",
    fuse = "True",
)
