load("//tools:defs.bzl", "go_library")

licenses(["notice"])

go_library(
    name = "fsmetric",
    srcs = ["fsmetric.go"],
    visibility = ["//pkg/sentry:internal"],
    deps = ["//pkg/metric"],
)
