// automatically generated by stateify.

package iouringfs

import (
	"gvisor.dev/gvisor/pkg/state"
)

func (fd *FileDescription) StateTypeName() string {
	return "pkg/sentry/fsimpl/iouringfs.FileDescription"
}

func (fd *FileDescription) StateFields() []string {
	return []string{
		"vfsfd",
		"FileDescriptionDefaultImpl",
		"DentryMetadataFileDescriptionImpl",
		"NoLockFD",
		"rbmf",
		"sqemf",
		"ioRings",
		"ioRingsBuf",
		"sqesBuf",
		"cqesBuf",
	}
}

func (fd *FileDescription) beforeSave() {}

// +checklocksignore
func (fd *FileDescription) StateSave(stateSinkObject state.Sink) {
	fd.beforeSave()
	stateSinkObject.Save(0, &fd.vfsfd)
	stateSinkObject.Save(1, &fd.FileDescriptionDefaultImpl)
	stateSinkObject.Save(2, &fd.DentryMetadataFileDescriptionImpl)
	stateSinkObject.Save(3, &fd.NoLockFD)
	stateSinkObject.Save(4, &fd.rbmf)
	stateSinkObject.Save(5, &fd.sqemf)
	stateSinkObject.Save(6, &fd.ioRings)
	stateSinkObject.Save(7, &fd.ioRingsBuf)
	stateSinkObject.Save(8, &fd.sqesBuf)
	stateSinkObject.Save(9, &fd.cqesBuf)
}

func (fd *FileDescription) afterLoad() {}

// +checklocksignore
func (fd *FileDescription) StateLoad(stateSourceObject state.Source) {
	stateSourceObject.Load(0, &fd.vfsfd)
	stateSourceObject.Load(1, &fd.FileDescriptionDefaultImpl)
	stateSourceObject.Load(2, &fd.DentryMetadataFileDescriptionImpl)
	stateSourceObject.Load(3, &fd.NoLockFD)
	stateSourceObject.Load(4, &fd.rbmf)
	stateSourceObject.Load(5, &fd.sqemf)
	stateSourceObject.Load(6, &fd.ioRings)
	stateSourceObject.Load(7, &fd.ioRingsBuf)
	stateSourceObject.Load(8, &fd.sqesBuf)
	stateSourceObject.Load(9, &fd.cqesBuf)
}

func init() {
	state.Register((*FileDescription)(nil))
}
