// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/sentry/arch/registers.proto

package gvisor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AMD64Registers struct {
	Rax                  uint64   `protobuf:"varint,1,opt,name=rax,proto3" json:"rax,omitempty"`
	Rbx                  uint64   `protobuf:"varint,2,opt,name=rbx,proto3" json:"rbx,omitempty"`
	Rcx                  uint64   `protobuf:"varint,3,opt,name=rcx,proto3" json:"rcx,omitempty"`
	Rdx                  uint64   `protobuf:"varint,4,opt,name=rdx,proto3" json:"rdx,omitempty"`
	Rsi                  uint64   `protobuf:"varint,5,opt,name=rsi,proto3" json:"rsi,omitempty"`
	Rdi                  uint64   `protobuf:"varint,6,opt,name=rdi,proto3" json:"rdi,omitempty"`
	Rsp                  uint64   `protobuf:"varint,7,opt,name=rsp,proto3" json:"rsp,omitempty"`
	Rbp                  uint64   `protobuf:"varint,8,opt,name=rbp,proto3" json:"rbp,omitempty"`
	R8                   uint64   `protobuf:"varint,9,opt,name=r8,proto3" json:"r8,omitempty"`
	R9                   uint64   `protobuf:"varint,10,opt,name=r9,proto3" json:"r9,omitempty"`
	R10                  uint64   `protobuf:"varint,11,opt,name=r10,proto3" json:"r10,omitempty"`
	R11                  uint64   `protobuf:"varint,12,opt,name=r11,proto3" json:"r11,omitempty"`
	R12                  uint64   `protobuf:"varint,13,opt,name=r12,proto3" json:"r12,omitempty"`
	R13                  uint64   `protobuf:"varint,14,opt,name=r13,proto3" json:"r13,omitempty"`
	R14                  uint64   `protobuf:"varint,15,opt,name=r14,proto3" json:"r14,omitempty"`
	R15                  uint64   `protobuf:"varint,16,opt,name=r15,proto3" json:"r15,omitempty"`
	Rip                  uint64   `protobuf:"varint,17,opt,name=rip,proto3" json:"rip,omitempty"`
	Rflags               uint64   `protobuf:"varint,18,opt,name=rflags,proto3" json:"rflags,omitempty"`
	OrigRax              uint64   `protobuf:"varint,19,opt,name=orig_rax,json=origRax,proto3" json:"orig_rax,omitempty"`
	Cs                   uint64   `protobuf:"varint,20,opt,name=cs,proto3" json:"cs,omitempty"`
	Ds                   uint64   `protobuf:"varint,21,opt,name=ds,proto3" json:"ds,omitempty"`
	Es                   uint64   `protobuf:"varint,22,opt,name=es,proto3" json:"es,omitempty"`
	Fs                   uint64   `protobuf:"varint,23,opt,name=fs,proto3" json:"fs,omitempty"`
	Gs                   uint64   `protobuf:"varint,24,opt,name=gs,proto3" json:"gs,omitempty"`
	Ss                   uint64   `protobuf:"varint,25,opt,name=ss,proto3" json:"ss,omitempty"`
	FsBase               uint64   `protobuf:"varint,26,opt,name=fs_base,json=fsBase,proto3" json:"fs_base,omitempty"`
	GsBase               uint64   `protobuf:"varint,27,opt,name=gs_base,json=gsBase,proto3" json:"gs_base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AMD64Registers) Reset()         { *m = AMD64Registers{} }
func (m *AMD64Registers) String() string { return proto.CompactTextString(m) }
func (*AMD64Registers) ProtoMessage()    {}
func (*AMD64Registers) Descriptor() ([]byte, []int) {
	return fileDescriptor_082b7510610e0457, []int{0}
}

func (m *AMD64Registers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AMD64Registers.Unmarshal(m, b)
}
func (m *AMD64Registers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AMD64Registers.Marshal(b, m, deterministic)
}
func (m *AMD64Registers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AMD64Registers.Merge(m, src)
}
func (m *AMD64Registers) XXX_Size() int {
	return xxx_messageInfo_AMD64Registers.Size(m)
}
func (m *AMD64Registers) XXX_DiscardUnknown() {
	xxx_messageInfo_AMD64Registers.DiscardUnknown(m)
}

var xxx_messageInfo_AMD64Registers proto.InternalMessageInfo

func (m *AMD64Registers) GetRax() uint64 {
	if m != nil {
		return m.Rax
	}
	return 0
}

func (m *AMD64Registers) GetRbx() uint64 {
	if m != nil {
		return m.Rbx
	}
	return 0
}

func (m *AMD64Registers) GetRcx() uint64 {
	if m != nil {
		return m.Rcx
	}
	return 0
}

func (m *AMD64Registers) GetRdx() uint64 {
	if m != nil {
		return m.Rdx
	}
	return 0
}

func (m *AMD64Registers) GetRsi() uint64 {
	if m != nil {
		return m.Rsi
	}
	return 0
}

func (m *AMD64Registers) GetRdi() uint64 {
	if m != nil {
		return m.Rdi
	}
	return 0
}

func (m *AMD64Registers) GetRsp() uint64 {
	if m != nil {
		return m.Rsp
	}
	return 0
}

func (m *AMD64Registers) GetRbp() uint64 {
	if m != nil {
		return m.Rbp
	}
	return 0
}

func (m *AMD64Registers) GetR8() uint64 {
	if m != nil {
		return m.R8
	}
	return 0
}

func (m *AMD64Registers) GetR9() uint64 {
	if m != nil {
		return m.R9
	}
	return 0
}

func (m *AMD64Registers) GetR10() uint64 {
	if m != nil {
		return m.R10
	}
	return 0
}

func (m *AMD64Registers) GetR11() uint64 {
	if m != nil {
		return m.R11
	}
	return 0
}

func (m *AMD64Registers) GetR12() uint64 {
	if m != nil {
		return m.R12
	}
	return 0
}

func (m *AMD64Registers) GetR13() uint64 {
	if m != nil {
		return m.R13
	}
	return 0
}

func (m *AMD64Registers) GetR14() uint64 {
	if m != nil {
		return m.R14
	}
	return 0
}

func (m *AMD64Registers) GetR15() uint64 {
	if m != nil {
		return m.R15
	}
	return 0
}

func (m *AMD64Registers) GetRip() uint64 {
	if m != nil {
		return m.Rip
	}
	return 0
}

func (m *AMD64Registers) GetRflags() uint64 {
	if m != nil {
		return m.Rflags
	}
	return 0
}

func (m *AMD64Registers) GetOrigRax() uint64 {
	if m != nil {
		return m.OrigRax
	}
	return 0
}

func (m *AMD64Registers) GetCs() uint64 {
	if m != nil {
		return m.Cs
	}
	return 0
}

func (m *AMD64Registers) GetDs() uint64 {
	if m != nil {
		return m.Ds
	}
	return 0
}

func (m *AMD64Registers) GetEs() uint64 {
	if m != nil {
		return m.Es
	}
	return 0
}

func (m *AMD64Registers) GetFs() uint64 {
	if m != nil {
		return m.Fs
	}
	return 0
}

func (m *AMD64Registers) GetGs() uint64 {
	if m != nil {
		return m.Gs
	}
	return 0
}

func (m *AMD64Registers) GetSs() uint64 {
	if m != nil {
		return m.Ss
	}
	return 0
}

func (m *AMD64Registers) GetFsBase() uint64 {
	if m != nil {
		return m.FsBase
	}
	return 0
}

func (m *AMD64Registers) GetGsBase() uint64 {
	if m != nil {
		return m.GsBase
	}
	return 0
}

type ARM64Registers struct {
	R0                   uint64   `protobuf:"varint,1,opt,name=r0,proto3" json:"r0,omitempty"`
	R1                   uint64   `protobuf:"varint,2,opt,name=r1,proto3" json:"r1,omitempty"`
	R2                   uint64   `protobuf:"varint,3,opt,name=r2,proto3" json:"r2,omitempty"`
	R3                   uint64   `protobuf:"varint,4,opt,name=r3,proto3" json:"r3,omitempty"`
	R4                   uint64   `protobuf:"varint,5,opt,name=r4,proto3" json:"r4,omitempty"`
	R5                   uint64   `protobuf:"varint,6,opt,name=r5,proto3" json:"r5,omitempty"`
	R6                   uint64   `protobuf:"varint,7,opt,name=r6,proto3" json:"r6,omitempty"`
	R7                   uint64   `protobuf:"varint,8,opt,name=r7,proto3" json:"r7,omitempty"`
	R8                   uint64   `protobuf:"varint,9,opt,name=r8,proto3" json:"r8,omitempty"`
	R9                   uint64   `protobuf:"varint,10,opt,name=r9,proto3" json:"r9,omitempty"`
	R10                  uint64   `protobuf:"varint,11,opt,name=r10,proto3" json:"r10,omitempty"`
	R11                  uint64   `protobuf:"varint,12,opt,name=r11,proto3" json:"r11,omitempty"`
	R12                  uint64   `protobuf:"varint,13,opt,name=r12,proto3" json:"r12,omitempty"`
	R13                  uint64   `protobuf:"varint,14,opt,name=r13,proto3" json:"r13,omitempty"`
	R14                  uint64   `protobuf:"varint,15,opt,name=r14,proto3" json:"r14,omitempty"`
	R15                  uint64   `protobuf:"varint,16,opt,name=r15,proto3" json:"r15,omitempty"`
	R16                  uint64   `protobuf:"varint,17,opt,name=r16,proto3" json:"r16,omitempty"`
	R17                  uint64   `protobuf:"varint,18,opt,name=r17,proto3" json:"r17,omitempty"`
	R18                  uint64   `protobuf:"varint,19,opt,name=r18,proto3" json:"r18,omitempty"`
	R19                  uint64   `protobuf:"varint,20,opt,name=r19,proto3" json:"r19,omitempty"`
	R20                  uint64   `protobuf:"varint,21,opt,name=r20,proto3" json:"r20,omitempty"`
	R21                  uint64   `protobuf:"varint,22,opt,name=r21,proto3" json:"r21,omitempty"`
	R22                  uint64   `protobuf:"varint,23,opt,name=r22,proto3" json:"r22,omitempty"`
	R23                  uint64   `protobuf:"varint,24,opt,name=r23,proto3" json:"r23,omitempty"`
	R24                  uint64   `protobuf:"varint,25,opt,name=r24,proto3" json:"r24,omitempty"`
	R25                  uint64   `protobuf:"varint,26,opt,name=r25,proto3" json:"r25,omitempty"`
	R26                  uint64   `protobuf:"varint,27,opt,name=r26,proto3" json:"r26,omitempty"`
	R27                  uint64   `protobuf:"varint,28,opt,name=r27,proto3" json:"r27,omitempty"`
	R28                  uint64   `protobuf:"varint,29,opt,name=r28,proto3" json:"r28,omitempty"`
	R29                  uint64   `protobuf:"varint,30,opt,name=r29,proto3" json:"r29,omitempty"`
	R30                  uint64   `protobuf:"varint,31,opt,name=r30,proto3" json:"r30,omitempty"`
	Sp                   uint64   `protobuf:"varint,32,opt,name=sp,proto3" json:"sp,omitempty"`
	Pc                   uint64   `protobuf:"varint,33,opt,name=pc,proto3" json:"pc,omitempty"`
	Pstate               uint64   `protobuf:"varint,34,opt,name=pstate,proto3" json:"pstate,omitempty"`
	Tls                  uint64   `protobuf:"varint,35,opt,name=tls,proto3" json:"tls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ARM64Registers) Reset()         { *m = ARM64Registers{} }
func (m *ARM64Registers) String() string { return proto.CompactTextString(m) }
func (*ARM64Registers) ProtoMessage()    {}
func (*ARM64Registers) Descriptor() ([]byte, []int) {
	return fileDescriptor_082b7510610e0457, []int{1}
}

func (m *ARM64Registers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ARM64Registers.Unmarshal(m, b)
}
func (m *ARM64Registers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ARM64Registers.Marshal(b, m, deterministic)
}
func (m *ARM64Registers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ARM64Registers.Merge(m, src)
}
func (m *ARM64Registers) XXX_Size() int {
	return xxx_messageInfo_ARM64Registers.Size(m)
}
func (m *ARM64Registers) XXX_DiscardUnknown() {
	xxx_messageInfo_ARM64Registers.DiscardUnknown(m)
}

var xxx_messageInfo_ARM64Registers proto.InternalMessageInfo

func (m *ARM64Registers) GetR0() uint64 {
	if m != nil {
		return m.R0
	}
	return 0
}

func (m *ARM64Registers) GetR1() uint64 {
	if m != nil {
		return m.R1
	}
	return 0
}

func (m *ARM64Registers) GetR2() uint64 {
	if m != nil {
		return m.R2
	}
	return 0
}

func (m *ARM64Registers) GetR3() uint64 {
	if m != nil {
		return m.R3
	}
	return 0
}

func (m *ARM64Registers) GetR4() uint64 {
	if m != nil {
		return m.R4
	}
	return 0
}

func (m *ARM64Registers) GetR5() uint64 {
	if m != nil {
		return m.R5
	}
	return 0
}

func (m *ARM64Registers) GetR6() uint64 {
	if m != nil {
		return m.R6
	}
	return 0
}

func (m *ARM64Registers) GetR7() uint64 {
	if m != nil {
		return m.R7
	}
	return 0
}

func (m *ARM64Registers) GetR8() uint64 {
	if m != nil {
		return m.R8
	}
	return 0
}

func (m *ARM64Registers) GetR9() uint64 {
	if m != nil {
		return m.R9
	}
	return 0
}

func (m *ARM64Registers) GetR10() uint64 {
	if m != nil {
		return m.R10
	}
	return 0
}

func (m *ARM64Registers) GetR11() uint64 {
	if m != nil {
		return m.R11
	}
	return 0
}

func (m *ARM64Registers) GetR12() uint64 {
	if m != nil {
		return m.R12
	}
	return 0
}

func (m *ARM64Registers) GetR13() uint64 {
	if m != nil {
		return m.R13
	}
	return 0
}

func (m *ARM64Registers) GetR14() uint64 {
	if m != nil {
		return m.R14
	}
	return 0
}

func (m *ARM64Registers) GetR15() uint64 {
	if m != nil {
		return m.R15
	}
	return 0
}

func (m *ARM64Registers) GetR16() uint64 {
	if m != nil {
		return m.R16
	}
	return 0
}

func (m *ARM64Registers) GetR17() uint64 {
	if m != nil {
		return m.R17
	}
	return 0
}

func (m *ARM64Registers) GetR18() uint64 {
	if m != nil {
		return m.R18
	}
	return 0
}

func (m *ARM64Registers) GetR19() uint64 {
	if m != nil {
		return m.R19
	}
	return 0
}

func (m *ARM64Registers) GetR20() uint64 {
	if m != nil {
		return m.R20
	}
	return 0
}

func (m *ARM64Registers) GetR21() uint64 {
	if m != nil {
		return m.R21
	}
	return 0
}

func (m *ARM64Registers) GetR22() uint64 {
	if m != nil {
		return m.R22
	}
	return 0
}

func (m *ARM64Registers) GetR23() uint64 {
	if m != nil {
		return m.R23
	}
	return 0
}

func (m *ARM64Registers) GetR24() uint64 {
	if m != nil {
		return m.R24
	}
	return 0
}

func (m *ARM64Registers) GetR25() uint64 {
	if m != nil {
		return m.R25
	}
	return 0
}

func (m *ARM64Registers) GetR26() uint64 {
	if m != nil {
		return m.R26
	}
	return 0
}

func (m *ARM64Registers) GetR27() uint64 {
	if m != nil {
		return m.R27
	}
	return 0
}

func (m *ARM64Registers) GetR28() uint64 {
	if m != nil {
		return m.R28
	}
	return 0
}

func (m *ARM64Registers) GetR29() uint64 {
	if m != nil {
		return m.R29
	}
	return 0
}

func (m *ARM64Registers) GetR30() uint64 {
	if m != nil {
		return m.R30
	}
	return 0
}

func (m *ARM64Registers) GetSp() uint64 {
	if m != nil {
		return m.Sp
	}
	return 0
}

func (m *ARM64Registers) GetPc() uint64 {
	if m != nil {
		return m.Pc
	}
	return 0
}

func (m *ARM64Registers) GetPstate() uint64 {
	if m != nil {
		return m.Pstate
	}
	return 0
}

func (m *ARM64Registers) GetTls() uint64 {
	if m != nil {
		return m.Tls
	}
	return 0
}

type Registers struct {
	// Types that are valid to be assigned to Arch:
	//	*Registers_Amd64
	//	*Registers_Arm64
	Arch                 isRegisters_Arch `protobuf_oneof:"arch"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Registers) Reset()         { *m = Registers{} }
func (m *Registers) String() string { return proto.CompactTextString(m) }
func (*Registers) ProtoMessage()    {}
func (*Registers) Descriptor() ([]byte, []int) {
	return fileDescriptor_082b7510610e0457, []int{2}
}

func (m *Registers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Registers.Unmarshal(m, b)
}
func (m *Registers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Registers.Marshal(b, m, deterministic)
}
func (m *Registers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Registers.Merge(m, src)
}
func (m *Registers) XXX_Size() int {
	return xxx_messageInfo_Registers.Size(m)
}
func (m *Registers) XXX_DiscardUnknown() {
	xxx_messageInfo_Registers.DiscardUnknown(m)
}

var xxx_messageInfo_Registers proto.InternalMessageInfo

type isRegisters_Arch interface {
	isRegisters_Arch()
}

type Registers_Amd64 struct {
	Amd64 *AMD64Registers `protobuf:"bytes,1,opt,name=amd64,proto3,oneof"`
}

type Registers_Arm64 struct {
	Arm64 *ARM64Registers `protobuf:"bytes,2,opt,name=arm64,proto3,oneof"`
}

func (*Registers_Amd64) isRegisters_Arch() {}

func (*Registers_Arm64) isRegisters_Arch() {}

func (m *Registers) GetArch() isRegisters_Arch {
	if m != nil {
		return m.Arch
	}
	return nil
}

func (m *Registers) GetAmd64() *AMD64Registers {
	if x, ok := m.GetArch().(*Registers_Amd64); ok {
		return x.Amd64
	}
	return nil
}

func (m *Registers) GetArm64() *ARM64Registers {
	if x, ok := m.GetArch().(*Registers_Arm64); ok {
		return x.Arm64
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Registers) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Registers_Amd64)(nil),
		(*Registers_Arm64)(nil),
	}
}

func init() {
	proto.RegisterType((*AMD64Registers)(nil), "gvisor.AMD64Registers")
	proto.RegisterType((*ARM64Registers)(nil), "gvisor.ARM64Registers")
	proto.RegisterType((*Registers)(nil), "gvisor.Registers")
}

func init() { proto.RegisterFile("pkg/sentry/arch/registers.proto", fileDescriptor_082b7510610e0457) }

var fileDescriptor_082b7510610e0457 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0x4b, 0x72, 0xd3, 0x40,
	0x10, 0x86, 0xc9, 0xc4, 0x71, 0x92, 0x09, 0x84, 0x20, 0xc0, 0xe9, 0xf0, 0x4a, 0x30, 0x1b, 0x56,
	0xb6, 0x5e, 0x96, 0xed, 0x25, 0x29, 0x16, 0x6c, 0xb2, 0xf1, 0x05, 0x52, 0xb2, 0x2c, 0x0b, 0x15,
	0x0e, 0x9e, 0x9a, 0x56, 0x51, 0x66, 0xcd, 0x95, 0x39, 0x00, 0xd5, 0x8f, 0x81, 0xe4, 0x06, 0xec,
	0xfa, 0xfb, 0xa6, 0x25, 0x8d, 0xf4, 0xb7, 0xc6, 0x5e, 0xba, 0x6f, 0xcd, 0x18, 0xeb, 0xef, 0x9d,
	0xff, 0x39, 0x2e, 0x7d, 0xf5, 0x75, 0xec, 0xeb, 0xa6, 0xc5, 0xae, 0xf6, 0x38, 0x72, 0x7e, 0xdb,
	0x6d, 0xa3, 0x7e, 0xf3, 0xa3, 0xc5, 0xad, 0x1f, 0xfe, 0xea, 0xd9, 0xd3, 0x4f, 0x37, 0x9f, 0x8b,
	0x7c, 0x11, 0x1a, 0xa2, 0x33, 0xbb, 0xef, 0xcb, 0x1d, 0xec, 0x5d, 0xed, 0x7d, 0xec, 0x2d, 0xa8,
	0x64, 0xb3, 0xdc, 0x81, 0x51, 0xb3, 0x14, 0x53, 0xed, 0x60, 0x5f, 0x4d, 0x25, 0x66, 0xb5, 0x83,
	0x9e, 0x9a, 0x95, 0x18, 0x6c, 0xe1, 0x40, 0x0d, 0xb6, 0xd2, 0xd3, 0x42, 0x3f, 0xf4, 0x88, 0x41,
	0x07, 0x87, 0xa1, 0xc7, 0xc9, 0xb3, 0x1c, 0x1c, 0x85, 0x67, 0xb9, 0xe8, 0xd4, 0x1a, 0x3f, 0x83,
	0x63, 0x16, 0xc6, 0xcf, 0x98, 0xe7, 0x60, 0x95, 0xe7, 0x7c, 0x45, 0x12, 0xc3, 0x89, 0x5e, 0x91,
	0xc4, 0x62, 0x12, 0x78, 0x1c, 0x4c, 0x22, 0x26, 0x85, 0x27, 0xc1, 0xa4, 0x62, 0x32, 0x38, 0x0d,
	0x26, 0x13, 0x93, 0xc3, 0xd3, 0x60, 0x72, 0x31, 0x13, 0x38, 0x0b, 0x66, 0xc2, 0xa6, 0x75, 0xf0,
	0x4c, 0x4d, 0xeb, 0xa2, 0x81, 0xed, 0xfb, 0xf5, 0xa6, 0x6c, 0x10, 0x22, 0x96, 0x4a, 0xd1, 0x85,
	0x3d, 0xda, 0xfa, 0xb6, 0xb9, 0xa5, 0x4f, 0xf9, 0x9c, 0x57, 0x0e, 0x89, 0x17, 0xe5, 0x8e, 0x5e,
	0xa0, 0x42, 0x78, 0x21, 0x2f, 0x50, 0x21, 0xf1, 0x0a, 0xe1, 0xa5, 0xf0, 0x8a, 0xb9, 0x46, 0x18,
	0x08, 0xd7, 0xcc, 0x6b, 0x84, 0x73, 0xe1, 0x35, 0x73, 0x83, 0x00, 0xc2, 0x0d, 0x33, 0x22, 0x5c,
	0x08, 0x23, 0x46, 0xe7, 0xf6, 0x70, 0x8d, 0xb7, 0xcb, 0x12, 0x6b, 0x78, 0x25, 0x7b, 0x5a, 0xe3,
	0x75, 0x89, 0x35, 0x2d, 0x34, 0xba, 0xf0, 0x5a, 0x16, 0x1a, 0x5e, 0x18, 0xfe, 0xa6, 0x29, 0x58,
	0xdc, 0xdc, 0x9f, 0x02, 0xfa, 0xca, 0xb1, 0x0e, 0x81, 0xf1, 0x31, 0x73, 0xa2, 0x23, 0x60, 0x7c,
	0xc2, 0x9c, 0xea, 0x00, 0x18, 0x9f, 0x32, 0x67, 0x1a, 0xbf, 0xf1, 0x19, 0x73, 0xae, 0xe1, 0x1b,
	0x9f, 0x33, 0x4f, 0x34, 0x7a, 0xe3, 0x27, 0xcc, 0x85, 0x06, 0x6f, 0x7c, 0xc1, 0x3c, 0xd5, 0xd8,
	0x8d, 0x9f, 0xfe, 0x77, 0xa9, 0x27, 0xc5, 0xdf, 0xd4, 0x93, 0x42, 0xcc, 0x54, 0x23, 0xa7, 0x52,
	0xcc, 0x4c, 0xa3, 0xa6, 0x52, 0xcc, 0x5c, 0x73, 0xa6, 0x92, 0x4d, 0x1a, 0x6b, 0xd2, 0x54, 0x8a,
	0x49, 0x34, 0x6b, 0x2a, 0xc5, 0xa4, 0x9a, 0x36, 0x95, 0x62, 0x32, 0xcd, 0x9b, 0x4a, 0x31, 0xb9,
	0x26, 0x4e, 0xa5, 0x98, 0x89, 0xc6, 0x4d, 0xa5, 0x98, 0x42, 0x73, 0xa6, 0x52, 0xcc, 0x14, 0xde,
	0x04, 0x23, 0x7b, 0x4e, 0x67, 0xf0, 0x36, 0x18, 0xd9, 0x73, 0x3a, 0x87, 0x77, 0xc1, 0xc8, 0x9e,
	0xb3, 0x18, 0x2e, 0xd5, 0x64, 0x3c, 0x09, 0xe8, 0xe0, 0x4a, 0xc7, 0x8d, 0xff, 0x4f, 0x57, 0xc1,
	0x7b, 0x61, 0x57, 0xd1, 0x1f, 0xe1, 0xb0, 0x2b, 0xbb, 0x1a, 0x86, 0x32, 0x64, 0x42, 0x74, 0xa7,
	0x6e, 0x83, 0xf0, 0x41, 0xee, 0xd4, 0x6d, 0x70, 0x88, 0xf6, 0xf8, 0xdf, 0xc0, 0x8d, 0xec, 0x41,
	0x79, 0xb7, 0x2a, 0x72, 0x9e, 0xb9, 0x93, 0x74, 0x30, 0x92, 0x13, 0x6a, 0xf4, 0xf0, 0x74, 0xfa,
	0xf2, 0x68, 0x21, 0x6d, 0xdc, 0xef, 0xef, 0x8a, 0x9c, 0x67, 0xf2, 0x7e, 0xff, 0x83, 0x39, 0xe6,
	0x7e, 0x6a, 0xbb, 0xee, 0xdb, 0x1e, 0x9d, 0x84, 0xcb, 0x3e, 0x1f, 0x80, 0xd9, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xd3, 0xa0, 0x97, 0xf1, 0x23, 0x05, 0x00, 0x00,
}
