load("//tools:defs.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "bigquery",
    testonly = 1,
    srcs = ["bigquery.go"],
    deps = ["@com_google_cloud_go_bigquery//:go_default_library"],
)
