// automatically generated by stateify.

package checkpoint

import (
	"context"

	"gvisor.dev/gvisor/pkg/state"
)

func (id *ResourceID) StateTypeName() string {
	return "pkg/sentry/checkpoint.ResourceID"
}

func (id *ResourceID) StateFields() []string {
	return []string{
		"ContainerName",
		"Path",
	}
}

func (id *ResourceID) beforeSave() {}

// +checklocksignore
func (id *ResourceID) StateSave(stateSinkObject state.Sink) {
	id.beforeSave()
	stateSinkObject.Save(0, &id.ContainerName)
	stateSinkObject.Save(1, &id.Path)
}

func (id *ResourceID) afterLoad(context.Context) {}

// +checklocksignore
func (id *ResourceID) StateLoad(ctx context.Context, stateSourceObject state.Source) {
	stateSourceObject.Load(0, &id.ContainerName)
	stateSourceObject.Load(1, &id.Path)
}

func init() {
	state.Register((*ResourceID)(nil))
}
