load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "common",
    srcs = ["common.go"],
    importpath = "gvisor.dev/gvisor/test/runtimes/common",
    visibility = ["//:sandbox"],
)
