// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/shim/v1/taskserver/task_server.proto

package gvisor_task_v1_Task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WaitRequest_WaitType int32

const (
	WaitRequest_UNKNOWN      WaitRequest_WaitType = 0
	WaitRequest_CHECKPOINT   WaitRequest_WaitType = 1
	WaitRequest_RESTORE      WaitRequest_WaitType = 2
	WaitRequest_FSCHECKPOINT WaitRequest_WaitType = 3
	WaitRequest_FSRESTORE    WaitRequest_WaitType = 4
)

// Enum value maps for WaitRequest_WaitType.
var (
	WaitRequest_WaitType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CHECKPOINT",
		2: "RESTORE",
		3: "FSCHECKPOINT",
		4: "FSRESTORE",
	}
	WaitRequest_WaitType_value = map[string]int32{
		"UNKNOWN":      0,
		"CHECKPOINT":   1,
		"RESTORE":      2,
		"FSCHECKPOINT": 3,
		"FSRESTORE":    4,
	}
)

func (x WaitRequest_WaitType) Enum() *WaitRequest_WaitType {
	p := new(WaitRequest_WaitType)
	*p = x
	return p
}

func (x WaitRequest_WaitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WaitRequest_WaitType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_shim_v1_taskserver_task_server_proto_enumTypes[0].Descriptor()
}

func (WaitRequest_WaitType) Type() protoreflect.EnumType {
	return &file_pkg_shim_v1_taskserver_task_server_proto_enumTypes[0]
}

func (x WaitRequest_WaitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WaitRequest_WaitType.Descriptor instead.
func (WaitRequest_WaitType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_shim_v1_taskserver_task_server_proto_rawDescGZIP(), []int{3, 0}
}

type Debug struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DebugLog      string                 `protobuf:"bytes,1,opt,name=debug_log,json=debugLog,proto3" json:"debug_log,omitempty"`
	DebugLogFd    int32                  `protobuf:"varint,2,opt,name=debug_log_fd,json=debugLogFd,proto3" json:"debug_log_fd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Debug) Reset() {
	*x = Debug{}
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Debug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Debug) ProtoMessage() {}

func (x *Debug) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Debug.ProtoReflect.Descriptor instead.
func (*Debug) Descriptor() ([]byte, []int) {
	return file_pkg_shim_v1_taskserver_task_server_proto_rawDescGZIP(), []int{0}
}

func (x *Debug) GetDebugLog() string {
	if x != nil {
		return x.DebugLog
	}
	return ""
}

func (x *Debug) GetDebugLogFd() int32 {
	if x != nil {
		return x.DebugLogFd
	}
	return 0
}

type CheckpointRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ImagePath                 string                 `protobuf:"bytes,2,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	Direct                    bool                   `protobuf:"varint,3,opt,name=direct,proto3" json:"direct,omitempty"`
	LeaveRunning              bool                   `protobuf:"varint,4,opt,name=leave_running,json=leaveRunning,proto3" json:"leave_running,omitempty"`
	FsCheckpoint              bool                   `protobuf:"varint,5,opt,name=fs_checkpoint,json=fsCheckpoint,proto3" json:"fs_checkpoint,omitempty"`
	Compression               string                 `protobuf:"bytes,6,opt,name=compression,proto3" json:"compression,omitempty"`
	ExcludeCommittedZeroPages bool                   `protobuf:"varint,7,opt,name=exclude_committed_zero_pages,json=excludeCommittedZeroPages,proto3" json:"exclude_committed_zero_pages,omitempty"`
	SaveRestoreExecArgv       string                 `protobuf:"bytes,8,opt,name=save_restore_exec_argv,json=saveRestoreExecArgv,proto3" json:"save_restore_exec_argv,omitempty"`
	SaveRestoreExecTimeout    string                 `protobuf:"bytes,9,opt,name=save_restore_exec_timeout,json=saveRestoreExecTimeout,proto3" json:"save_restore_exec_timeout,omitempty"`
	CudaCheckpointPath        string                 `protobuf:"bytes,10,opt,name=cuda_checkpoint_path,json=cudaCheckpointPath,proto3" json:"cuda_checkpoint_path,omitempty"`
	Debug                     *Debug                 `protobuf:"bytes,11,opt,name=debug,proto3" json:"debug,omitempty"`
	CudaCheckpointSequential  bool                   `protobuf:"varint,12,opt,name=cuda_checkpoint_sequential,json=cudaCheckpointSequential,proto3" json:"cuda_checkpoint_sequential,omitempty"`
	WorkPath                  string                 `protobuf:"bytes,13,opt,name=work_path,json=workPath,proto3" json:"work_path,omitempty"`
	FsPath                    string                 `protobuf:"bytes,14,opt,name=fs_path,json=fsPath,proto3" json:"fs_path,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_pkg_shim_v1_taskserver_task_server_proto_rawDescGZIP(), []int{1}
}

func (x *CheckpointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckpointRequest) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *CheckpointRequest) GetDirect() bool {
	if x != nil {
		return x.Direct
	}
	return false
}

func (x *CheckpointRequest) GetLeaveRunning() bool {
	if x != nil {
		return x.LeaveRunning
	}
	return false
}

func (x *CheckpointRequest) GetFsCheckpoint() bool {
	if x != nil {
		return x.FsCheckpoint
	}
	return false
}

func (x *CheckpointRequest) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *CheckpointRequest) GetExcludeCommittedZeroPages() bool {
	if x != nil {
		return x.ExcludeCommittedZeroPages
	}
	return false
}

func (x *CheckpointRequest) GetSaveRestoreExecArgv() string {
	if x != nil {
		return x.SaveRestoreExecArgv
	}
	return ""
}

func (x *CheckpointRequest) GetSaveRestoreExecTimeout() string {
	if x != nil {
		return x.SaveRestoreExecTimeout
	}
	return ""
}

func (x *CheckpointRequest) GetCudaCheckpointPath() string {
	if x != nil {
		return x.CudaCheckpointPath
	}
	return ""
}

func (x *CheckpointRequest) GetDebug() *Debug {
	if x != nil {
		return x.Debug
	}
	return nil
}

func (x *CheckpointRequest) GetCudaCheckpointSequential() bool {
	if x != nil {
		return x.CudaCheckpointSequential
	}
	return false
}

func (x *CheckpointRequest) GetWorkPath() string {
	if x != nil {
		return x.WorkPath
	}
	return ""
}

func (x *CheckpointRequest) GetFsPath() string {
	if x != nil {
		return x.FsPath
	}
	return ""
}

type CheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_pkg_shim_v1_taskserver_task_server_proto_rawDescGZIP(), []int{2}
}

type WaitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WaitType      WaitRequest_WaitType   `protobuf:"varint,2,opt,name=wait_type,json=waitType,proto3,enum=gvisor.task.WaitRequest_WaitType" json:"wait_type,omitempty"`
	Debug         *Debug                 `protobuf:"bytes,3,opt,name=debug,proto3" json:"debug,omitempty"`
	Pid           int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	RootPid       int32                  `protobuf:"varint,5,opt,name=root_pid,json=rootPid,proto3" json:"root_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitRequest) Reset() {
	*x = WaitRequest{}
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitRequest) ProtoMessage() {}

func (x *WaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitRequest.ProtoReflect.Descriptor instead.
func (*WaitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_shim_v1_taskserver_task_server_proto_rawDescGZIP(), []int{3}
}

func (x *WaitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WaitRequest) GetWaitType() WaitRequest_WaitType {
	if x != nil {
		return x.WaitType
	}
	return WaitRequest_UNKNOWN
}

func (x *WaitRequest) GetDebug() *Debug {
	if x != nil {
		return x.Debug
	}
	return nil
}

func (x *WaitRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *WaitRequest) GetRootPid() int32 {
	if x != nil {
		return x.RootPid
	}
	return 0
}

type WaitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitStatus    int32                  `protobuf:"varint,1,opt,name=exit_status,json=exitStatus,proto3" json:"exit_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitResponse) Reset() {
	*x = WaitResponse{}
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitResponse) ProtoMessage() {}

func (x *WaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitResponse.ProtoReflect.Descriptor instead.
func (*WaitResponse) Descriptor() ([]byte, []int) {
	return file_pkg_shim_v1_taskserver_task_server_proto_rawDescGZIP(), []int{4}
}

func (x *WaitResponse) GetExitStatus() int32 {
	if x != nil {
		return x.ExitStatus
	}
	return 0
}

type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Debug         *Debug                 `protobuf:"bytes,2,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_shim_v1_taskserver_task_server_proto_rawDescGZIP(), []int{5}
}

func (x *StateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StateRequest) GetDebug() *Debug {
	if x != nil {
		return x.Debug
	}
	return nil
}

type StateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_shim_v1_taskserver_task_server_proto_rawDescGZIP(), []int{6}
}

func (x *StateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StateResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StateResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_shim_v1_taskserver_task_server_proto_rawDescGZIP(), []int{7}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shim_v1_taskserver_task_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_shim_v1_taskserver_task_server_proto_rawDescGZIP(), []int{8}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_pkg_shim_v1_taskserver_task_server_proto protoreflect.FileDescriptor

const file_pkg_shim_v1_taskserver_task_server_proto_rawDesc = "" +
	"\n" +
	"(pkg/shim/v1/taskserver/task_server.proto\x12\vgvisor.task\"F\n" +
	"\x05Debug\x12\x1b\n" +
	"\tdebug_log\x18\x01 \x01(\tR\bdebugLog\x12 \n" +
	"\fdebug_log_fd\x18\x02 \x01(\x05R\n" +
	"debugLogFd\"\xc7\x04\n" +
	"\x11CheckpointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"image_path\x18\x02 \x01(\tR\timagePath\x12\x16\n" +
	"\x06direct\x18\x03 \x01(\bR\x06direct\x12#\n" +
	"\rleave_running\x18\x04 \x01(\bR\fleaveRunning\x12#\n" +
	"\rfs_checkpoint\x18\x05 \x01(\bR\ffsCheckpoint\x12 \n" +
	"\vcompression\x18\x06 \x01(\tR\vcompression\x12?\n" +
	"\x1cexclude_committed_zero_pages\x18\a \x01(\bR\x19excludeCommittedZeroPages\x123\n" +
	"\x16save_restore_exec_argv\x18\b \x01(\tR\x13saveRestoreExecArgv\x129\n" +
	"\x19save_restore_exec_timeout\x18\t \x01(\tR\x16saveRestoreExecTimeout\x120\n" +
	"\x14cuda_checkpoint_path\x18\n" +
	" \x01(\tR\x12cudaCheckpointPath\x12(\n" +
	"\x05debug\x18\v \x01(\v2\x12.gvisor.task.DebugR\x05debug\x12<\n" +
	"\x1acuda_checkpoint_sequential\x18\f \x01(\bR\x18cudaCheckpointSequential\x12\x1b\n" +
	"\twork_path\x18\r \x01(\tR\bworkPath\x12\x17\n" +
	"\afs_path\x18\x0e \x01(\tR\x06fsPath\"\x14\n" +
	"\x12CheckpointResponse\"\x8b\x02\n" +
	"\vWaitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\twait_type\x18\x02 \x01(\x0e2!.gvisor.task.WaitRequest.WaitTypeR\bwaitType\x12(\n" +
	"\x05debug\x18\x03 \x01(\v2\x12.gvisor.task.DebugR\x05debug\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12\x19\n" +
	"\broot_pid\x18\x05 \x01(\x05R\arootPid\"U\n" +
	"\bWaitType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"CHECKPOINT\x10\x01\x12\v\n" +
	"\aRESTORE\x10\x02\x12\x10\n" +
	"\fFSCHECKPOINT\x10\x03\x12\r\n" +
	"\tFSRESTORE\x10\x04\"/\n" +
	"\fWaitResponse\x12\x1f\n" +
	"\vexit_status\x18\x01 \x01(\x05R\n" +
	"exitStatus\"H\n" +
	"\fStateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x05debug\x18\x02 \x01(\v2\x12.gvisor.task.DebugR\x05debug\"G\n" +
	"\rStateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\"\x10\n" +
	"\x0eVersionRequest\"+\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion2\x9f\x02\n" +
	"\vTaskService\x12M\n" +
	"\n" +
	"Checkpoint\x12\x1e.gvisor.task.CheckpointRequest\x1a\x1f.gvisor.task.CheckpointResponse\x12;\n" +
	"\x04Wait\x12\x18.gvisor.task.WaitRequest\x1a\x19.gvisor.task.WaitResponse\x12>\n" +
	"\x05State\x12\x19.gvisor.task.StateRequest\x1a\x1a.gvisor.task.StateResponse\x12D\n" +
	"\aVersion\x12\x1b.gvisor.task.VersionRequest\x1a\x1c.gvisor.task.VersionResponseB\x15Z\x13gvisor.task.v1.Taskb\x06proto3"

var (
	file_pkg_shim_v1_taskserver_task_server_proto_rawDescOnce sync.Once
	file_pkg_shim_v1_taskserver_task_server_proto_rawDescData []byte
)

func file_pkg_shim_v1_taskserver_task_server_proto_rawDescGZIP() []byte {
	file_pkg_shim_v1_taskserver_task_server_proto_rawDescOnce.Do(func() {
		file_pkg_shim_v1_taskserver_task_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_shim_v1_taskserver_task_server_proto_rawDesc), len(file_pkg_shim_v1_taskserver_task_server_proto_rawDesc)))
	})
	return file_pkg_shim_v1_taskserver_task_server_proto_rawDescData
}

var file_pkg_shim_v1_taskserver_task_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_shim_v1_taskserver_task_server_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_shim_v1_taskserver_task_server_proto_goTypes = []any{
	(WaitRequest_WaitType)(0),  // 0: gvisor.task.WaitRequest.WaitType
	(*Debug)(nil),              // 1: gvisor.task.Debug
	(*CheckpointRequest)(nil),  // 2: gvisor.task.CheckpointRequest
	(*CheckpointResponse)(nil), // 3: gvisor.task.CheckpointResponse
	(*WaitRequest)(nil),        // 4: gvisor.task.WaitRequest
	(*WaitResponse)(nil),       // 5: gvisor.task.WaitResponse
	(*StateRequest)(nil),       // 6: gvisor.task.StateRequest
	(*StateResponse)(nil),      // 7: gvisor.task.StateResponse
	(*VersionRequest)(nil),     // 8: gvisor.task.VersionRequest
	(*VersionResponse)(nil),    // 9: gvisor.task.VersionResponse
}
var file_pkg_shim_v1_taskserver_task_server_proto_depIdxs = []int32{
	1, // 0: gvisor.task.CheckpointRequest.debug:type_name -> gvisor.task.Debug
	0, // 1: gvisor.task.WaitRequest.wait_type:type_name -> gvisor.task.WaitRequest.WaitType
	1, // 2: gvisor.task.WaitRequest.debug:type_name -> gvisor.task.Debug
	1, // 3: gvisor.task.StateRequest.debug:type_name -> gvisor.task.Debug
	2, // 4: gvisor.task.TaskService.Checkpoint:input_type -> gvisor.task.CheckpointRequest
	4, // 5: gvisor.task.TaskService.Wait:input_type -> gvisor.task.WaitRequest
	6, // 6: gvisor.task.TaskService.State:input_type -> gvisor.task.StateRequest
	8, // 7: gvisor.task.TaskService.Version:input_type -> gvisor.task.VersionRequest
	3, // 8: gvisor.task.TaskService.Checkpoint:output_type -> gvisor.task.CheckpointResponse
	5, // 9: gvisor.task.TaskService.Wait:output_type -> gvisor.task.WaitResponse
	7, // 10: gvisor.task.TaskService.State:output_type -> gvisor.task.StateResponse
	9, // 11: gvisor.task.TaskService.Version:output_type -> gvisor.task.VersionResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_shim_v1_taskserver_task_server_proto_init() }
func file_pkg_shim_v1_taskserver_task_server_proto_init() {
	if File_pkg_shim_v1_taskserver_task_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_shim_v1_taskserver_task_server_proto_rawDesc), len(file_pkg_shim_v1_taskserver_task_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_shim_v1_taskserver_task_server_proto_goTypes,
		DependencyIndexes: file_pkg_shim_v1_taskserver_task_server_proto_depIdxs,
		EnumInfos:         file_pkg_shim_v1_taskserver_task_server_proto_enumTypes,
		MessageInfos:      file_pkg_shim_v1_taskserver_task_server_proto_msgTypes,
	}.Build()
	File_pkg_shim_v1_taskserver_task_server_proto = out.File
	file_pkg_shim_v1_taskserver_task_server_proto_goTypes = nil
	file_pkg_shim_v1_taskserver_task_server_proto_depIdxs = nil
}
