load("//tools:defs.bzl", "go_binary")

package(
    default_applicable_licenses = ["//:license"],
    licenses = ["notice"],
)

go_binary(
    name = "stucktasks",
    srcs = ["stucktasks.go"],
    deps = [
        "//runsc/flag",
    ],
)
