#!/bin/bash

# Copyright 2024 The gVisor Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Add runtime test jobs only if test results in the case are outdated.

set -xeo pipefail

exec 1>&2

cmd="$1"
shift
export TOTAL_PARTITIONS=10
shift

if [[ -z "$TEST_CHECK_UP_TO_DATE_FILE" ]]; then
  echo "TEST_CHECK_UP_TO_DATE_FILE isn't set"
  exit 1
fi

function cleanup() {
  if [[ -f "$TEST_CHECK_UP_TO_DATE_FILE" ]]; then
    rm -rf $TEST_CHECK_UP_TO_DATE_FILE
  fi
}

touch $TEST_CHECK_UP_TO_DATE_FILE
trap cleanup EXIT

# Check if any tests need running by checking "all" (1/1).
if PARTITION=1 TOTAL_PARTITIONS=$TOTAL_PARTITIONS make $cmd-runtime-tests; then
  exit 0
fi

( export CMD="$cmd"
  export RUNTIME_ARGS="$@"
  export BUILDKITE_LABEL="$BUILDKITE_LABEL"
  python3 tools/pipeline_generator.py
) |  buildkite-agent pipeline upload
