{
  "checkunsafe": {
    "exclude_files": {
      "/external/": "allowed: not subject to unsafe naming rules"
    }
  },
  "composites": {
    "exclude_files": {
      ".*_test.go": "allowed: allow for convenience in tests",
      "/external/": "allowed: not subject to style constraint",
      "/pkg/metric/metric.go": "allowed: verbose protos",
      "/pkg/sentry/socket/rpcinet/.*": "allowed: verbose protos",
      "/pkg/state/(encode|decode).go": "allowed: verbose protos",
      "/pkg/sentry/fs/dev/random.go": "fix: gvisor.dev/gvisor/pkg/sentry/safemem.FromIOReader composite literal uses unkeyed fields",
      "/pkg/sentry/fs/fdpipe/pipe.go": "fix: gvisor.dev/gvisor/pkg/secio.FullReader composite literal uses unkeyed fields",
      "/pkg/sentry/fs/fdpipe/pipe.go": "fix: gvisor.dev/gvisor/pkg/sentry/safemem.FromIOReader composite literal uses unkeyed fields",
      "/pkg/sentry/fs/fdpipe/pipe.go": "fix: gvisor.dev/gvisor/pkg/sentry/safemem.FromIOWriter composite literal uses unkeyed fields",
      "/pkg/sentry/fs/fdpipe/pipe_state.go": "fix: gvisor.dev/gvisor/pkg/sentry/fs.ErrSaveRejection composite literal uses unkeyed fields",
      "/pkg/sentry/fs/fsutil/dirty_set_impl.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.MappableRange composite literal uses unkeyed fields",
      "/pkg/sentry/fs/fsutil/file_range_set.go": "fix: gvisor.dev/gvisor/pkg/sentry/platform.FileRange composite literal uses unkeyed fields",
      "/pkg/sentry/fs/fsutil/file_range_set_impl.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.MappableRange composite literal uses unkeyed fields",
      "/pkg/sentry/fs/fsutil/frame_ref_set_impl.go": "fix: gvisor.dev/gvisor/pkg/sentry/platform.FileRange composite literal uses unkeyed fields",
      "/pkg/sentry/fs/fsutil/host_file_mapper.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.MappableRange composite literal uses unkeyed fields",
      "/pkg/sentry/fs/fsutil/inode_cached.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.BusError composite literal uses unkeyed fields",
      "/pkg/sentry/fs/fsutil/inode_cached.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.MappableRange composite literal uses unkeyed fields",
      "/pkg/sentry/fs/fsutil/inode_cached.go": "fix: gvisor.dev/gvisor/pkg/sentry/pgalloc.EvictableRange composite literal uses unkeyed fields",
      "/pkg/sentry/fs/gofer/handles.go": "fix: gvisor.dev/gvisor/pkg/sentry/safemem.FromIOReader composite literal uses unkeyed fields",
      "/pkg/sentry/fs/gofer/handles.go": "fix: gvisor.dev/gvisor/pkg/sentry/safemem.FromIOWriter composite literal uses unkeyed fields",
      "/pkg/sentry/fs/gofer/inode_state.go": "fix: gvisor.dev/gvisor/pkg/sentry/fs.ErrCorruption composite literal uses unkeyed fields",
      "/pkg/sentry/fs/gofer/inode_state.go": "fix: gvisor.dev/gvisor/pkg/sentry/fs.ErrSaveRejection composite literal uses unkeyed fields",
      "/pkg/sentry/fs/host/file.go": "fix: gvisor.dev/gvisor/pkg/sentry/safemem.FromIOReader composite literal uses unkeyed fields",
      "/pkg/sentry/fs/host/file.go": "fix: gvisor.dev/gvisor/pkg/sentry/safemem.FromIOWriter composite literal uses unkeyed fields",
      "/pkg/sentry/fs/host/inode.go": "fix: gvisor.dev/gvisor/pkg/sentry/safemem.FromIOReader composite literal uses unkeyed fields",
      "/pkg/sentry/fs/host/inode.go": "fix: gvisor.dev/gvisor/pkg/sentry/safemem.FromIOWriter composite literal uses unkeyed fields",
      "/pkg/sentry/fs/host/inode_state.go": "fix: gvisor.dev/gvisor/pkg/sentry/fs.ErrCorruption composite literal uses unkeyed fields",
      "/pkg/sentry/fs/host/inode_state.go": "fix: gvisor.dev/gvisor/pkg/sentry/fs.ErrSaveRejection composite literal uses unkeyed fields",
      "/pkg/sentry/fs/host/util.go": "fix: gvisor.dev/gvisor/pkg/sentry/fs.FileOwner composite literal uses unkeyed fields",
      "/pkg/sentry/fs/host/util_unsafe.go": "fix: syscall.Timespec composite literal uses unkeyed fields",
      "/pkg/sentry/fs/proc/inode.go": "fix: gvisor.dev/gvisor/pkg/sentry/fs.FileOwner composite literal uses unkeyed fields",
      "/pkg/sentry/fs/tmpfs/inode_file.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.BusError composite literal uses unkeyed fields",
      "/pkg/sentry/fs/tmpfs/inode_file.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.MappableRange composite literal uses unkeyed fields",
      "/pkg/sentry/fs/tty/dir.go": "fix: gvisor.dev/gvisor/pkg/sentry/fs.FileOwner composite literal uses unkeyed fields",
      "/pkg/sentry/fsimpl/ext/extent_file.go": "fix: gvisor.dev/gvisor/pkg/sentry/fsimpl/ext/disklayout.ExtentNode composite literal uses unkeyed fields",
      "/pkg/sentry/kernel/fd_table.go": "fix: gvisor.dev/gvisor/pkg/sentry/fs/lock.LockRange composite literal uses unkeyed fields",
      "/pkg/sentry/kernel/seccomp.go": "fix: gvisor.dev/gvisor/pkg/bpf.InputBytes composite literal uses unkeyed fields",
      "/pkg/sentry/kernel/shm/shm.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.BusError composite literal uses unkeyed fields",
      "/pkg/sentry/kernel/shm/shm.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.MappableRange composite literal uses unkeyed fields",
      "/pkg/sentry/kernel/task_context.go": "fix: gvisor.dev/gvisor/pkg/sentry/arch.Stack composite literal uses unkeyed fields",
      "/pkg/sentry/kernel/task_signals.go": "fix: gvisor.dev/gvisor/pkg/sentry/arch.Stack composite literal uses unkeyed fields",
      "/pkg/sentry/loader/elf.go": "fix: gvisor.dev/gvisor/pkg/sentry/arch.AuxEntry composite literal uses unkeyed fields",
      "/pkg/sentry/loader/loader.go": "fix: gvisor.dev/gvisor/pkg/sentry/arch.AuxEntry composite literal uses unkeyed fields",
      "/pkg/sentry/loader/loader.go": "fix: gvisor.dev/gvisor/pkg/sentry/arch.Stack composite literal uses unkeyed fields",
      "/pkg/sentry/memmap/memmap.go": "fix: gvisor.dev/gvisor/pkg/sentry/platform.FileRange composite literal uses unkeyed fields",
      "/pkg/sentry/mm/address_space.go": "fix: gvisor.dev/gvisor/pkg/sentry/usermem.AddrRange composite literal uses unkeyed fields",
      "/pkg/sentry/mm/aio_context.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.BusError composite literal uses unkeyed fields",
      "/pkg/sentry/mm/aio_context.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.MappableRange composite literal uses unkeyed fields",
      "/pkg/sentry/mm/file_refcount_set.go": "fix: gvisor.dev/gvisor/pkg/sentry/platform.FileRange composite literal uses unkeyed fields",
      "/pkg/sentry/mm/io.go": "fix: gvisor.dev/gvisor/pkg/sentry/usermem.AddrRange composite literal uses unkeyed fields",
      "/pkg/sentry/mm/pma.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.BusError composite literal uses unkeyed fields",
      "/pkg/sentry/mm/pma.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.MappableRange composite literal uses unkeyed fields",
      "/pkg/sentry/mm/pma.go": "fix: gvisor.dev/gvisor/pkg/sentry/platform.FileRange composite literal uses unkeyed fields",
      "/pkg/sentry/mm/pma.go": "fix: gvisor.dev/gvisor/pkg/sentry/safemem.BlockSeqReader composite literal uses unkeyed fields",
      "/pkg/sentry/mm/pma.go": "fix: gvisor.dev/gvisor/pkg/sentry/usermem.AddrRange composite literal uses unkeyed fields",
      "/pkg/sentry/mm/pma_set.go": "fix: gvisor.dev/gvisor/pkg/sentry/usermem.AddrRange composite literal uses unkeyed fields",
      "/pkg/sentry/mm/special_mappable.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.BusError composite literal uses unkeyed fields",
      "/pkg/sentry/mm/special_mappable.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.MappableRange composite literal uses unkeyed fields",
      "/pkg/sentry/mm/syscalls.go": "fix: gvisor.dev/gvisor/pkg/sentry/usermem.AddrRange composite literal uses unkeyed fields",
      "/pkg/sentry/mm/vma.go": "fix: gvisor.dev/gvisor/pkg/sentry/memmap.MappableRange composite literal uses unkeyed fields",
      "/pkg/sentry/mm/vma.go": "fix: gvisor.dev/gvisor/pkg/sentry/usermem.AddrRange composite literal uses unkeyed fields",
      "/pkg/sentry/mm/vma_set.go": "fix: gvisor.dev/gvisor/pkg/sentry/usermem.AddrRange composite literal uses unkeyed fields",
      "/pkg/sentry/pgalloc/pgalloc.go": "fix: gvisor.dev/gvisor/pkg/sentry/platform.FileRange composite literal uses unkeyed fields",
      "/pkg/sentry/pgalloc/usage_set.go": "fix: gvisor.dev/gvisor/pkg/sentry/platform.FileRange composite literal uses unkeyed fields",
      "/pkg/sentry/socket/epsocket/epsocket.go": "fix: gvisor.dev/gvisor/pkg/sentry/safemem.FromVecReaderFunc composite literal uses unkeyed fields",
      "/pkg/sentry/socket/unix/io.go": "fix: gvisor.dev/gvisor/pkg/sentry/safemem.FromVecReaderFunc composite literal uses unkeyed fields",
      "/pkg/sentry/socket/unix/io.go": "fix: gvisor.dev/gvisor/pkg/sentry/safemem.FromVecWriterFunc composite literal uses unkeyed fields",
      "/pkg/sentry/syscalls/epoll.go": "fix: gvisor.dev/gvisor/pkg/sentry/kernel/epoll.FileIdentifier composite literal uses unkeyed fields",
      "/pkg/sentry/syscalls/linux/sys_random.go": "fix: gvisor.dev/gvisor/pkg/sentry/safemem.FromIOReader composite literal uses unkeyed fields",
      "/pkg/tcpip/network/arp/arp.go": "fix: gvisor.dev/gvisor/pkg/tcpip/stack.NetworkEndpointID composite literal uses unkeyed fields",
      "/pkg/tcpip/sample/tun_tcp_connect/main.go": "fix: gvisor.dev/gvisor/pkg/tcpip.FullAddress composite literal uses unkeyed fields",
      "/pkg/tcpip/sample/tun_tcp_echo/main.go": "fix: gvisor.dev/gvisor/pkg/tcpip.FullAddress composite literal uses unkeyed fields",
      "/pkg/tcpip/stack/nic.go": "fix: gvisor.dev/gvisor/pkg/tcpip.AddressWithPrefix composite literal uses unkeyed fields",
      "/pkg/tcpip/transport/tcp/endpoint_state.go": "fix: gvisor.dev/gvisor/pkg/tcpip.ErrSaveRejection composite literal uses unkeyed fields",
      "/pkg/tcpip/transport/tcp/sack_scoreboard.go": "fix: gvisor.dev/gvisor/pkg/tcpip/header.SACKBlock composite literal uses unkeyed fields",
      "/pkg/tcpip/transport/tcp/segment.go": "fix: gvisor.dev/gvisor/pkg/tcpip/header.SACKBlock composite literal uses unkeyed fields",
      "/pkg/tcpip/transport/tcp/snd.go": "fix: gvisor.dev/gvisor/pkg/tcpip/header.SACKBlock composite literal uses unkeyed fields",
      "/pkg/tcpip/transport/tcp/testing/context/context.go": "fix: gvisor.dev/gvisor/pkg/tcpip/transport/tcp.ReceiveBufferSizeOption composite literal uses unkeyed fields",
      "/pkg/tcpip/transport/tcp/testing/context/context.go": "fix: gvisor.dev/gvisor/pkg/tcpip/transport/tcp.SendBufferSizeOption composite literal uses unkeyed fields",
      "/pkg/tcpip/transport/udp/endpoint.go": "fix: gvisor.dev/gvisor/pkg/tcpip.MulticastInterfaceOption composite literal uses unkeyed fields",
      "/runsc/boot/compat.go": "fix: gvisor.dev/gvisor/pkg/log.K8sJSONEmitter composite literal uses unkeyed fields",
      "/runsc/boot/loader.go": "fix: gvisor.dev/gvisor/pkg/sentry/socket/epsocket.Stack composite literal uses unkeyed fields",
      "/runsc/cmd/exec.go": "fix: gvisor.dev/gvisor/pkg/urpc.FilePayload composite literal uses unkeyed fields",
      "/runsc/main.go": "fix: gvisor.dev/gvisor/pkg/log.GoogleEmitter composite literal uses unkeyed fields",
      "/runsc/main.go": "fix: gvisor.dev/gvisor/pkg/log.JSONEmitter composite literal uses unkeyed fields"
    }
  },
  "copylocks": {
    "exclude_files": {
      ".*_state_autogen.go": "fix: m.Failf copies by value",
      "/pkg/log/json.go": "fix: Emit passes lock by value: gvisor.dev/gvisor/pkg/log.JSONEmitter contains gvisor.dev/gvisor/pkg/log.Writer contains sync.Mutex",
      "/pkg/log/json_k8s.go": "fix: Emit passes lock by value: gvisor.dev/gvisor/pkg/log.K8sJSONEmitter contains gvisor.dev/gvisor/pkg/log.Writer contains sync.Mutex",
      "/pkg/log/log_test.go": "fix: call of fmt.Printf copies lock value: gvisor.dev/gvisor/pkg/log.Writer contains sync.Mutex",
      "/pkg/sentry/fs/host/socket_test.go": "fix: call of t.Errorf copies lock value: gvisor.dev/gvisor/pkg/sentry/fs/host.ConnectedEndpoint contains gvisor.dev/gvisor/pkg/refs.AtomicRefCount contains sync.Mutex",
      "/pkg/sentry/kernel/syscalls_state.go": "fix: assignment copies lock value to *s: gvisor.dev/gvisor/pkg/sentry/kernel.SyscallTable contains gvisor.dev/gvisor/pkg/sentry/kernel.SyscallFlagsTable contains sync.Mutex",
      "/pkg/sentry/kernel/time/time.go": "fix: Readiness passes lock by value: gvisor.dev/gvisor/pkg/sentry/kernel/time.ClockEventsQueue contains gvisor.dev/gvisor/pkg/waiter.Queue contains sync.RWMutex"
    }
  },
  "nilness": {
    "exclude_files": {
      "/com_github_vishvananda_netlink/route_linux.go": "allowed: false positive",
      "/org_golang_x_tools/go/packages/golist.go": "allowed: runtime internals",
      "/pkg/sentry/platform/kvm/kvm_test.go": "allowed: intentional"
    }
  },
  "printf": {
    "exclude_files": {
      ".*_abi_autogen_test.go": "fix: Sprintf format has insufficient args",
      "/pkg/eventchannel/event_test.go": "fix: Fatal call has possible formatting directive %v",
      "/pkg/segment/test/segment_test.go": "fix: Errorf format %d arg seg.Start is a func value, not called",
      "/pkg/sentry/fs/fdpipe/pipe_test.go": "fix: Errorf format %d arg f.FD is a func value, not called",
      "/pkg/sentry/fs/fdpipe/pipe_test.go": "fix: Errorf format %s has arg flags of wrong type gvisor.dev/gvisor/pkg/sentry/fs.FileFlags",
      "/pkg/tcpip/link/fdbased/endpoint.go": "fix: Sprintf format %v with arg p causes recursive String method call",
      "/pkg/tcpip/stack/stack_test.go": "fix: Fatalf format %s has arg nic1ProtoAddr of wrong type gvisor.dev/gvisor/pkg/tcpip.ProtocolAddress",
      "/pkg/tcpip/stack/stack_test.go": "fix: Fatalf format %s has arg nic2ProtoAddr of wrong type gvisor.dev/gvisor/pkg/tcpip.ProtocolAddress",
      "/pkg/tcpip/stack/stack_test.go": "fix: Fatalf format %s has arg protoAddr of wrong type gvisor.dev/gvisor/pkg/tcpip.ProtocolAddress",
      "/pkg/tcpip/tcpip_test.go": "fix: Error call has possible formatting directive %q",
      "/pkg/tcpip/transport/tcp/tcp_test.go": "fix: Errorf call needs 1 arg but has 2 args",
      "/pkg/tcpip/transport/udp/udp_test.go": "fix: Fatalf format %s has arg h.srcAddr of wrong type gvisor.dev/gvisor/pkg/tcpip.FullAddress",
      "/runsc/container/test_app/test_app.go": "fix: Fatal call has possible formatting directive %q",
      "/test/runtimes/runner.go": "fix: Skip call has possible formatting directive %q"
    }
  },
  "shadow": {
    "exclude_files": {
      ".*_test.go": "allowed: allow for convenience in tests",
      "/external/": "allowed: not subject to shadowing rules",
      "/pkg/cpuid/cpuid.go": "fix: declaration of 'bx' shadows declaration at line 950",
      "/pkg/cpuid/cpuid.go": "fix: declaration of 'cx' shadows declaration at line 950",
      "/pkg/cpuid/cpuid.go": "fix: declaration of 'dx' shadows declaration at line 950",
      "/pkg/p9/server.go": "fix: declaration of 'err' shadows declaration at line 410",
      "/pkg/p9/server.go": "fix: declaration of 'err' shadows declaration at line 514",
      "/pkg/p9/server.go": "fix: declaration of 'handler' shadows declaration at line 66",
      "/pkg/p9/transport.go": "fix: declaration of 'err' shadows declaration at line 172",
      "/pkg/p9/transport.go": "fix: declaration of 'filer' shadows declaration at line 59",
      "/pkg/p9/transport.go": "fix: declaration of 'payloader' shadows declaration at line 44",
      "/pkg/p9/transport_flipcall.go": "fix: declaration of 'filer' shadows declaration at line 59",
      "/pkg/p9/transport_flipcall.go": "fix: declaration of 'payloader' shadows declaration at line 44",
      "/pkg/sentry/fs/copy_up.go": "fix: declaration of 'err' shadows declaration at line 233",
      "/pkg/sentry/fs/dirent.go": "fix: declaration of 'err' shadows declaration at line 1513",
      "/pkg/sentry/fs/host/socket.go": "fix: declaration of 'err' shadows declaration at line 81",
      "/pkg/sentry/fs/mounts.go": "fix: declaration of 'err' shadows declaration at line 580",
      "/pkg/sentry/fs/proc/exec_args.go": "fix: declaration of 'err' shadows declaration at line 107",
      "/pkg/sentry/fs/ramfs/dir.go": "fix: declaration of 'err' shadows declaration at line 236",
      "/pkg/sentry/fsimpl/ext/extent_file.go": "fix: declaration of 'off' shadows declaration at line 101",
      "/pkg/sentry/fsimpl/ext/inode.go": "fix: declaration of 'inode' shadows declaration at line 41",
      "/pkg/sentry/kernel/abstract_socket_namespace.go": "fix: declaration of 'rc' shadows declaration at line 96",
      "/pkg/sentry/kernel/futex/futex.go": "fix: declaration of 'err' shadows declaration at line 740",
      "/pkg/sentry/kernel/task_run.go": "fix: declaration of 'err' shadows declaration at line 209",
      "/pkg/sentry/loader/elf.go": "fix: declaration of 'err' shadows declaration at line 486",
      "/pkg/sentry/loader/loader.go": "fix: declaration of 'err' shadows declaration at line 260",
      "/pkg/sentry/mm/io.go": "fix: declaration of 'err' shadows declaration at line 129",
      "/pkg/sentry/mm/io.go": "fix: declaration of 'err' shadows declaration at line 172",
      "/pkg/sentry/mm/io.go": "fix: declaration of 'err' shadows declaration at line 214",
      "/pkg/sentry/mm/io.go": "fix: declaration of 'err' shadows declaration at line 322",
      "/pkg/sentry/mm/io.go": "fix: declaration of 'err' shadows declaration at line 365",
      "/pkg/sentry/mm/io.go": "fix: declaration of 'err' shadows declaration at line 408",
      "/pkg/sentry/mm/pma.go": "fix: declaration of 'err' shadows declaration at line 268",
      "/pkg/sentry/mm/pma.go": "fix: declaration of 'err' shadows declaration at line 418",
      "/pkg/sentry/mm/syscalls.go": "fix: declaration of 'vma' shadows declaration at line 236",
      "/pkg/sentry/mm/syscalls.go": "fix: declaration of 'vseg' shadows declaration at line 365",
      "/pkg/sentry/platform/kvm/virtual_map.go": "fix: declaration of 'err' shadows declaration at line 67",
      "/pkg/sentry/socket/epsocket/epsocket.go": "fix: declaration of 'err' shadows declaration at line 2018",
      "/pkg/sentry/socket/epsocket/epsocket.go": "fix: declaration of 'iface' shadows declaration at line 2369",
      "/pkg/sentry/socket/netfilter/netfilter.go": "fix: declaration of 'metadata' shadows declaration at line 38",
      "/pkg/sentry/socket/netlink/socket.go": "fix: declaration of 'err' shadows declaration at line 562",
      "/pkg/sentry/socket/rpcinet/stack_unsafe.go": "fix: declaration of 'err' shadows declaration at line 135",
      "/pkg/sentry/syscalls/linux/sys_file.go": "fix: declaration of 'err' shadows declaration at line 133",
      "/pkg/sentry/syscalls/linux/sys_file.go": "fix: declaration of 'err' shadows declaration at line 1362",
      "/pkg/sentry/syscalls/linux/sys_file.go": "fix: declaration of 'err' shadows declaration at line 297",
      "/pkg/sentry/syscalls/linux/sys_file.go": "fix: declaration of 'err' shadows declaration at line 317",
      "/pkg/sentry/syscalls/linux/sys_file.go": "fix: declaration of 'fd' shadows declaration at line 872",
      "/pkg/sentry/syscalls/linux/sys_poll.go": "fix: declaration of 'err' shadows declaration at line 174",
      "/pkg/sentry/syscalls/linux/sys_poll.go": "fix: declaration of 'err' shadows declaration at line 438",
      "/pkg/sentry/syscalls/linux/sys_poll.go": "fix: declaration of 'err' shadows declaration at line 514",
      "/pkg/sentry/syscalls/linux/sys_read.go": "fix: declaration of 'err' shadows declaration at line 270",
      "/pkg/sentry/syscalls/linux/sys_rlimit.go": "fix: declaration of 'err' shadows declaration at line 154",
      "/pkg/sentry/syscalls/linux/sys_signal.go": "fix: declaration of 'err' shadows declaration at line 364",
      "/pkg/sentry/syscalls/linux/sys_splice.go": "fix: declaration of 'err' shadows declaration at line 124",
      "/pkg/sentry/syscalls/linux/sys_thread.go": "fix: declaration of 'err' shadows declaration at line 323",
      "/pkg/sentry/syscalls/linux/sys_thread.go": "fix: declaration of 'err' shadows declaration at line 71",
      "/pkg/sentry/syscalls/linux/sys_time.go": "fix: declaration of 'err' shadows declaration at line 226",
      "/pkg/sentry/syscalls/linux/sys_write.go": "fix: declaration of 'err' shadows declaration at line 241",
      "/pkg/sentry/time/sampler.go": "fix: declaration of 'sample' shadows declaration at line 85",
      "/pkg/sentry/usage/memory.go": "fix: declaration of 'err' shadows declaration at line 123",
      "/pkg/sentry/vfs/mount_unsafe.go": "fix: declaration of 'mountKey' shadows declaration at line 36",
      "/pkg/tcpip/link/fdbased/endpoint.go": "fix: declaration of 'err' shadows declaration at line 260",
      "/pkg/tcpip/network/ipv4/icmp.go": "fix: declaration of 'vv' shadows declaration at line 55",
      "/pkg/tcpip/stack/nic.go": "fix: declaration of 'n' shadows declaration at line 614",
      "/pkg/tcpip/stack/nic.go": "fix: declaration of 'ok' shadows declaration at line 314",
      "/pkg/tcpip/tcpip.go": "fix: declaration of 'v' shadows declaration at line 1005",
      "/pkg/tcpip/tcpip.go": "fix: declaration of 'v' shadows declaration at line 954",
      "/pkg/tcpip/transport/raw/endpoint.go": "fix: declaration of 'err' shadows declaration at line 223",
      "/pkg/tcpip/transport/tcp/endpoint.go": "fix: declaration of 'err' shadows declaration at line 1425",
      "/pkg/tcpip/transport/tcp/snd.go": "fix: declaration of 'seg' shadows declaration at line 1040",
      "/pkg/tcpip/transport/tcp/testing/context/context.go": "fix: declaration of 'err' shadows declaration at line 869",
      "/runsc/boot/fs.go": "fix: declaration of 'err' shadows declaration at line 911",
      "/runsc/boot/loader.go": "fix: declaration of 'err' shadows declaration at line 195",
      "/runsc/boot/loader.go": "fix: declaration of 'err' shadows declaration at line 519",
      "/runsc/boot/loader.go": "fix: declaration of 'err' shadows declaration at line 596",
      "/runsc/boot/user.go": "fix: declaration of 'err' shadows declaration at line 55",
      "/runsc/cmd/boot.go": "fix: declaration of 'err' shadows declaration at line 165",
      "/runsc/cmd/capability.go": "fix: declaration of 'err' shadows declaration at line 38",
      "/runsc/cmd/checkpoint.go": "fix: declaration of 'err' shadows declaration at line 78",
      "/runsc/cmd/do.go": "fix: declaration of 'err' shadows declaration at line 95",
      "/runsc/cmd/exec.go": "fix: declaration of 'err' shadows declaration at line 154",
      "/runsc/cmd/exec.go": "fix: declaration of 'err' shadows declaration at line 257",
      "/runsc/cmd/gofer.go": "fix: declaration of 'err' shadows declaration at line 104",
      "/runsc/container/container.go": "fix: declaration of 'err' shadows declaration at line 454",
      "/runsc/container/test_app/fds.go": "fix: declaration of 'err' shadows declaration at line 130",
      "/runsc/fsgofer/fsgofer.go": "fix: declaration of 'err' shadows declaration at line 467",
      "/runsc/fsgofer/fsgofer.go": "fix: declaration of 'err' shadows declaration at line 522",
      "/runsc/fsgofer/fsgofer.go": "fix: declaration of 'err' shadows declaration at line 720",
      "/runsc/fsgofer/fsgofer.go": "fix: declaration of 'err' shadows declaration at line 889",
      "/runsc/fsgofer/fsgofer.go": "fix: declaration of 'names' shadows declaration at line 999",
      "/runsc/sandbox/network.go": "fix: declaration of 'err' shadows declaration at line 170",
      "/runsc/sandbox/sandbox.go": "fix: declaration of 'err' shadows declaration at line 222",
      "/test/syscalls/syscall_test_runner.go": "fix: declaration of 'cmd' shadows declaration at line 226",
      "/test/syscalls/syscall_test_runner.go": "fix: declaration of 'err' shadows declaration at line 101"
    }
  },
  "structtag": {
    "exclude_files": {
      "/external/": "allowed: may use arbitrary tags"
    }
  },
  "unsafeptr": {
    "exclude_files": {
      ".*_test.go": "allowed: exclude tests",
      "/pkg/flipcall/flipcall_unsafe.go": "allowed: special case",
      "/pkg/sentry/fs/fsutil/host_file_mapper_unsafe.go": "allowed: special case",
      "/pkg/sentry/platform/kvm/(bluepill|machine)_unsafe.go": "allowed: special case",
      "/pkg/sentry/platform/ring0/pagetables/allocator_unsafe.go": "allowed: special case",
      "/pkg/sentry/platform/safecopy/safecopy_unsafe.go": "allowed: special case",
      "/pkg/sentry/vfs/mount_unsafe.go": "allowed: special case"
    }
  }
}
