load("//tools:defs.bzl", "go_library")

package(
    default_applicable_licenses = ["//:license"],
    licenses = ["notice"],
)

go_library(
    name = "bufferv2",
    srcs = [
        "buffer.go",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/buffer",
    ],
)
