package(licenses = ["notice"])  # Apache 2.0

load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "stateify",
    srcs = ["main.go"],
    visibility = ["//visibility:public"],
)
