load("//tools:defs.bzl", "go_library")

package(
    default_applicable_licenses = ["//:license"],
    licenses = ["notice"],
)

go_library(
    name = "test2",
    srcs = ["test2.go"],
    deps = ["//tools/checkescape/test1"],
)
