// automatically generated by stateify.

package ttydev

import (
	"gvisor.dev/gvisor/pkg/state"
)

func (x *ttyDevice) StateTypeName() string {
	return "pkg/sentry/devices/ttydev.ttyDevice"
}

func (x *ttyDevice) StateFields() []string {
	return []string{}
}

func (x *ttyDevice) beforeSave() {}

func (x *ttyDevice) StateSave(m state.Sink) {
	x.beforeSave()
}

func (x *ttyDevice) afterLoad() {}

func (x *ttyDevice) StateLoad(m state.Source) {
}

func init() {
	state.Register((*ttyDevice)(nil))
}
