// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.2
// source: pkg/sentry/vfs/events.proto

package events_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SentryMountPromiseBlockEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentryMountPromiseBlockEvent) Reset() {
	*x = SentryMountPromiseBlockEvent{}
	mi := &file_pkg_sentry_vfs_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentryMountPromiseBlockEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentryMountPromiseBlockEvent) ProtoMessage() {}

func (x *SentryMountPromiseBlockEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sentry_vfs_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentryMountPromiseBlockEvent.ProtoReflect.Descriptor instead.
func (*SentryMountPromiseBlockEvent) Descriptor() ([]byte, []int) {
	return file_pkg_sentry_vfs_events_proto_rawDescGZIP(), []int{0}
}

func (x *SentryMountPromiseBlockEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_pkg_sentry_vfs_events_proto protoreflect.FileDescriptor

const file_pkg_sentry_vfs_events_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/sentry/vfs/events.proto\x12\x06gvisor\"2\n" +
	"\x1cSentryMountPromiseBlockEvent\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04pathb\x06proto3"

var (
	file_pkg_sentry_vfs_events_proto_rawDescOnce sync.Once
	file_pkg_sentry_vfs_events_proto_rawDescData []byte
)

func file_pkg_sentry_vfs_events_proto_rawDescGZIP() []byte {
	file_pkg_sentry_vfs_events_proto_rawDescOnce.Do(func() {
		file_pkg_sentry_vfs_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_sentry_vfs_events_proto_rawDesc), len(file_pkg_sentry_vfs_events_proto_rawDesc)))
	})
	return file_pkg_sentry_vfs_events_proto_rawDescData
}

var file_pkg_sentry_vfs_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_sentry_vfs_events_proto_goTypes = []any{
	(*SentryMountPromiseBlockEvent)(nil), // 0: gvisor.SentryMountPromiseBlockEvent
}
var file_pkg_sentry_vfs_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_sentry_vfs_events_proto_init() }
func file_pkg_sentry_vfs_events_proto_init() {
	if File_pkg_sentry_vfs_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_sentry_vfs_events_proto_rawDesc), len(file_pkg_sentry_vfs_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_sentry_vfs_events_proto_goTypes,
		DependencyIndexes: file_pkg_sentry_vfs_events_proto_depIdxs,
		MessageInfos:      file_pkg_sentry_vfs_events_proto_msgTypes,
	}.Build()
	File_pkg_sentry_vfs_events_proto = out.File
	file_pkg_sentry_vfs_events_proto_goTypes = nil
	file_pkg_sentry_vfs_events_proto_depIdxs = nil
}
