name: CI

"on":
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: bazel
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo -E apt update && sudo -E apt install -y make

    - name: Checkout
      uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

    - name: build
      run: |
          mkdir -p bin
          make copy TARGETS=runsc DESTINATION=bin/

    - name: Upload runsc
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
          name: runsc
          path: bin/runsc
