name: CI

"on":
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: bazel
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo -E apt update && sudo -E apt install -y make

    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: build
      run: |
          mkdir -p bin
          make copy TARGETS=runsc DESTINATION=bin/

    - name: Upload runsc
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
          name: runsc
          path: bin/runsc
