# Labeler labels incoming pull requests.
name: "Labeler"
"on":
- pull_request

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # read labeler config
      pull-requests: write # apply labels to the PR
    steps:
    - uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6.2.0
      if: github.base_ref == null
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
